#include "exotic/autonomy/agents/in_memory_repository.hpp"
#include "exotic/autonomy/agents/scheduler_bridge.hpp"
#include "exotic/autonomy/resources/in_memory_repository.hpp"
#include "exotic/autonomy/scheduler/sqlite_repository.hpp"
#include "exotic/autonomy/scheduler/scheduler.hpp"
#include <cassert>
#include <thread>
using namespace exotic::autonomy;using namespace exotic::autonomy::agents;
namespace {class Approval final:public resources::BudgetApprovalVerifier{public:bool approves(resources::GovernanceApprovalId,ProposalId,double,TimePoint,std::string&r)override{r="approved";return true;}};class Inner final:public scheduler::ExecutionBridge{public:int calls{};scheduler::ExecutionResult execute(const scheduler::Job&,std::stop_token)override{++calls;return{true,scheduler::FailureClass::Permanent,"done"};}};}
int main(){auto db=std::filesystem::temp_directory_path()/"exotic-runtime-agent-stack.db";std::filesystem::remove(db);
std::filesystem::remove(db.string()+"-wal");std::filesystem::remove(db.string()+"-shm");{InMemoryAgentRepository agents;AgentRegistry registry{agents};CapabilityDefinition d;d.key="execute";d.name="Execute";registry.define_capability(d);AgentIdentity a;a.identity_key="worker";a.display_name="Worker";a.health=HealthState::Healthy;a.trust=TrustLevel::Elevated;a.workload.maximum_tasks=2;a.last_heartbeat_at=Clock::now();auto aid=registry.register_agent(a);registry.activate(aid);registry.heartbeat(aid,HealthState::Healthy,Availability::Available,a.workload);registry.grant_capability({aid,"execute",.9,.9,0,0,Clock::now()});AllowAllGovernanceCompatibility gov;AllowAllResourceCompatibility resCompat;CandidateScorer scorer{agents,registry,gov,resCompat};WorkAllocator allocator{agents,scorer};resources::InMemoryResourceRepository rr;Approval approval;resources::ResourceGovernor governor{rr,approval};resources::ResourceAccount account;account.scope=resources::AccountScope::Workspace;account.scope_id="test";account.name="test";account.limits={{resources::ResourceDimension::MoneyUsd,100,80,0,0},{resources::ResourceDimension::ConcurrencySlots,4,4,0,0}};auto accountId=governor.create_account(account);TaskRequirement req;req.capabilities={{"execute",.5,.5,true,1}};req.resource_account_id=accountId;req.resource_estimate={{resources::ResourceDimension::ConcurrencySlots,1}};req.maximum_team_cost_usd=5;FixedTaskRequirementPlanner planner{req};resources::EstimatedUsageMeter meter;AgentLearningEngine learning{agents};Inner inner;AgentOrchestratedExecutionBridge orchestration{agents,registry,allocator,gov,resCompat,governor,meter,learning,planner,inner};scheduler::SqliteSchedulerRepository sr{db};scheduler::BasicConditionEvaluator conditions;scheduler::DurableScheduler sched{sr,orchestration,conditions};sched.recover();sched.start(2);scheduler::Job j;j.objective_id=1;j.proposal_id=1;j.name="full-stack";j.idempotency_key="full-stack-1";auto id=sched.submit(j);for(int i=0;i<100;++i){auto v=sr.find_job(id);if(v&&v->status==scheduler::JobStatus::Completed)break;std::this_thread::sleep_for(std::chrono::milliseconds(20));}sched.request_stop();sched.join();auto done=sr.find_job(id);assert(done&&done->status==scheduler::JobStatus::Completed&&inner.calls==1);assert(agents.find_assignment_by_job(id));assert(rr.load_active_reservations().empty());}std::filesystem::remove(db);std::filesystem::remove(db.string()+"-wal");std::filesystem::remove(db.string()+"-shm");}
