#include "exotic/autonomy/agents/compatibility.hpp"
#include "exotic/autonomy/governance/service.hpp"
#include <cassert>
#include <map>
using namespace exotic::autonomy;using namespace exotic::autonomy::agents;using namespace exotic::autonomy::governance;
namespace {
class Repo final:public GovernanceRepository{
public:ApprovalRequestId next_request_id()override{return nr++;}DecisionId next_decision_id()override{return nd++;}GrantId next_grant_id()override{return ng++;}PolicyId next_policy_id()override{return np++;}EvidenceId next_evidence_id()override{return ne++;}
void save_request(const ApprovalRequest&r)override{requests[r.id]=r;}std::optional<ApprovalRequest> load_request(ApprovalRequestId id)override{auto i=requests.find(id);return i==requests.end()?std::nullopt:std::optional<ApprovalRequest>{i->second};}std::vector<ApprovalRequest> load_pending(TimePoint)override{std::vector<ApprovalRequest>o;for(auto&[id,r]:requests)if(r.status==ApprovalStatus::Pending)o.push_back(r);return o;}
void append_decision(const ApprovalDecision&d)override{decisions[d.request_id].push_back(d);}std::vector<ApprovalDecision> load_decisions(ApprovalRequestId id)override{return decisions[id];}
void save_grant(const CapabilityGrant&g)override{grants[g.subject_id].push_back(g);}std::vector<CapabilityGrant> load_grants(std::string_view id)override{return grants[std::string{id}];}
void save_policy(const PolicyVersion&p)override{policies.push_back(p);}std::vector<PolicyVersion> load_active_policies()override{std::vector<PolicyVersion>o;for(auto&p:policies)if(p.active)o.push_back(p);return o;}
void append_evidence(const DecisionEvidence&e)override{evidence[e.request_id].push_back(e);}std::vector<DecisionEvidence> load_evidence(ApprovalRequestId id)override{return evidence[id];}
void set_emergency_stop(bool active,std::string_view,std::string_view)override{stop=active;}bool emergency_stop_active()override{return stop;}
private:ApprovalRequestId nr{1};DecisionId nd{1};GrantId ng{1};PolicyId np{1};EvidenceId ne{1};bool stop{false};std::map<ApprovalRequestId,ApprovalRequest>requests;std::map<ApprovalRequestId,std::vector<ApprovalDecision>>decisions;std::map<std::string,std::vector<CapabilityGrant>>grants;std::vector<PolicyVersion>policies;std::map<ApprovalRequestId,std::vector<DecisionEvidence>>evidence;
};}
int main(){Repo repo;CapabilityGrant grant;grant.id=1;grant.subject_id="agent-1";grant.capability={"proposal.execute","proposal","*"};grant.maximum_autonomy=AutonomyLevel::Bounded;grant.budget_limit_usd=25.0;repo.save_grant(grant);PolicyVersion policy;policy.id=1;policy.name="agents";PolicyRule rule;rule.id="allow-operator";rule.effect=Effect::Allow;rule.action="proposal.execute";rule.resource_type="proposal";rule.required_role="operator";policy.rules.push_back(rule);repo.save_policy(policy);GovernanceService service{repo};AuthorityGate gate{service};GovernanceAgentCompatibility compatibility{gate,repo};AgentIdentity agent;agent.identity_key="agent-1";agent.roles={"operator"};TaskRequirement req;req.job_id=1;req.proposal_id=7;req.action="proposal.execute";req.maximum_team_cost_usd=10.0;auto allowed=compatibility.validate(agent,req);assert(allowed.allowed);PolicyVersion escalation;escalation.id=2;escalation.name="high-control";PolicyRule escalate;escalate.id="require-approval";escalate.effect=Effect::Escalate;escalate.action="proposal.execute";escalate.resource_type="proposal";escalation.rules.push_back(escalate);repo.save_policy(escalation);ApprovalRequest approval;approval.id=2;approval.proposal_id=7;approval.requester_id="planner";approval.action="proposal.execute";approval.resource={"proposal","7",{}};approval.risk=RiskLevel::High;approval.requested_budget_usd=20.0;approval.status=ApprovalStatus::Approved;approval.expires_at=Clock::now()+std::chrono::hours(1);repo.save_request(approval);req.governance_approval_id=2;grant.maximum_autonomy=AutonomyLevel::Bounded;auto approved=compatibility.validate(agent,req);assert(approved.allowed);repo.set_emergency_stop(true,"test","stop");auto stopped=compatibility.validate(agent,req);assert(!stopped.allowed);return 0;}
