#include "sqlite_repository.hpp"
#include "../persistence/transaction.hpp"
#include <algorithm>
#include <limits>
#include <stdexcept>

namespace exotic::autonomy::agents {
using persistence::Statement;
namespace {
std::int64_t sid(std::uint64_t v){if(v>static_cast<std::uint64_t>(std::numeric_limits<std::int64_t>::max()))throw std::overflow_error("Identifier exceeds SQLite range");return static_cast<std::int64_t>(v);} 
void bind_optional_time(Statement&s,std::size_t i,const std::optional<TimePoint>&v){if(v)s.bind(i,to_unix_milliseconds(*v));else s.bind_null(i);} 
std::optional<TimePoint> read_optional_time(const Statement&s,int c){if(s.column_is_null(c))return std::nullopt;return from_unix_milliseconds(s.column_int64(c));}
}

SqliteAgentRepository::SqliteAgentRepository(const std::filesystem::path&p):database_(p){migrate();}
void SqliteAgentRepository::migrate(){
    database_.execute("CREATE TABLE IF NOT EXISTS agent_schema_metadata(key TEXT PRIMARY KEY,value TEXT NOT NULL);");
    {
        Statement version{database_,"SELECT value FROM agent_schema_metadata WHERE key='schema_version';"};
        if(version.step()&&std::stoi(version.column_text(0))>6){
            throw std::runtime_error("Agent database schema is newer than this EXOTIC build");
        }
    }
    database_.execute("CREATE TABLE IF NOT EXISTS agent_schema_metadata(key TEXT PRIMARY KEY,value TEXT NOT NULL);"
    "CREATE TABLE IF NOT EXISTS agents(id INTEGER PRIMARY KEY,identity_key TEXT NOT NULL UNIQUE,display_name TEXT NOT NULL,status TEXT NOT NULL,availability TEXT NOT NULL,health TEXT NOT NULL,trust TEXT NOT NULL,specialist_title TEXT NOT NULL,primary_domain TEXT NOT NULL,specialty TEXT NOT NULL,description TEXT NOT NULL,runtime_kind TEXT NOT NULL,runtime_version TEXT NOT NULL,model_provider TEXT NOT NULL,model_name TEXT NOT NULL,model_version TEXT NOT NULL,endpoint TEXT NOT NULL,maximum_context_tokens INTEGER NOT NULL,supports_tools INTEGER NOT NULL,supports_parallel_work INTEGER NOT NULL,fixed_cost_usd REAL NOT NULL,hourly_cost_usd REAL NOT NULL,input_token_cost REAL NOT NULL,output_token_cost REAL NOT NULL,api_credits_per_task REAL NOT NULL,active_tasks INTEGER NOT NULL,maximum_tasks INTEGER NOT NULL,utilization REAL NOT NULL,workload_updated_ms INTEGER NOT NULL,resource_account_id INTEGER,registered_at_ms INTEGER NOT NULL,updated_at_ms INTEGER NOT NULL,revoked_at_ms INTEGER,last_heartbeat_at_ms INTEGER,revocation_reason TEXT NOT NULL);"
    "CREATE TABLE IF NOT EXISTS agent_roles(agent_id INTEGER NOT NULL,role TEXT NOT NULL,PRIMARY KEY(agent_id,role),FOREIGN KEY(agent_id) REFERENCES agents(id) ON DELETE CASCADE);"
    "CREATE TABLE IF NOT EXISTS agent_attributes(agent_id INTEGER NOT NULL,key TEXT NOT NULL,value TEXT NOT NULL,PRIMARY KEY(agent_id,key),FOREIGN KEY(agent_id) REFERENCES agents(id) ON DELETE CASCADE);"
    "CREATE TABLE IF NOT EXISTS agent_runtime_attributes(agent_id INTEGER NOT NULL,key TEXT NOT NULL,value TEXT NOT NULL,PRIMARY KEY(agent_id,key),FOREIGN KEY(agent_id) REFERENCES agents(id) ON DELETE CASCADE);"
    "CREATE TABLE IF NOT EXISTS agent_domains(agent_id INTEGER NOT NULL,domain TEXT NOT NULL,PRIMARY KEY(agent_id,domain),FOREIGN KEY(agent_id) REFERENCES agents(id) ON DELETE CASCADE);"
    "CREATE TABLE IF NOT EXISTS agent_tags(agent_id INTEGER NOT NULL,tag TEXT NOT NULL,PRIMARY KEY(agent_id,tag),FOREIGN KEY(agent_id) REFERENCES agents(id) ON DELETE CASCADE);"
    "CREATE TABLE IF NOT EXISTS capability_definitions(id INTEGER PRIMARY KEY,key TEXT NOT NULL UNIQUE,parent_key TEXT,domain TEXT NOT NULL,name TEXT NOT NULL,description TEXT NOT NULL,active INTEGER NOT NULL,created_at_ms INTEGER NOT NULL);"
    "CREATE TABLE IF NOT EXISTS capability_required_tools(capability_id INTEGER NOT NULL,tool_key TEXT NOT NULL,PRIMARY KEY(capability_id,tool_key),FOREIGN KEY(capability_id) REFERENCES capability_definitions(id) ON DELETE CASCADE);"
    "CREATE TABLE IF NOT EXISTS agent_capabilities(agent_id INTEGER NOT NULL,capability_key TEXT NOT NULL,proficiency REAL NOT NULL,reliability REAL NOT NULL,successful_uses INTEGER NOT NULL,failed_uses INTEGER NOT NULL,last_validated_at_ms INTEGER NOT NULL,PRIMARY KEY(agent_id,capability_key),FOREIGN KEY(agent_id) REFERENCES agents(id) ON DELETE CASCADE);"
    "CREATE TABLE IF NOT EXISTS agent_tool_permissions(agent_id INTEGER NOT NULL,tool_key TEXT NOT NULL,scope TEXT NOT NULL,allowed INTEGER NOT NULL,valid_from_ms INTEGER NOT NULL,valid_until_ms INTEGER,PRIMARY KEY(agent_id,tool_key,scope),FOREIGN KEY(agent_id) REFERENCES agents(id) ON DELETE CASCADE);"
    "CREATE TABLE IF NOT EXISTS agent_tool_operations(agent_id INTEGER NOT NULL,tool_key TEXT NOT NULL,scope TEXT NOT NULL,operation TEXT NOT NULL,PRIMARY KEY(agent_id,tool_key,scope,operation));"
    "CREATE TABLE IF NOT EXISTS capability_evidence(id INTEGER PRIMARY KEY,agent_id INTEGER NOT NULL,capability_key TEXT NOT NULL,evidence_type TEXT NOT NULL,reference TEXT NOT NULL,confidence REAL NOT NULL,payload_json TEXT NOT NULL,created_at_ms INTEGER NOT NULL,FOREIGN KEY(agent_id) REFERENCES agents(id));"
    "CREATE TABLE IF NOT EXISTS work_assignments(id INTEGER PRIMARY KEY,version INTEGER NOT NULL,job_id INTEGER NOT NULL UNIQUE,proposal_id INTEGER NOT NULL,status TEXT NOT NULL,action TEXT NOT NULL,domain TEXT NOT NULL,minimum_trust TEXT NOT NULL,minimum_team_size INTEGER NOT NULL,preferred_team_size INTEGER NOT NULL,maximum_team_size INTEGER NOT NULL,plan_mode TEXT NOT NULL,supervisor_required INTEGER NOT NULL,supervisor_capability TEXT,maximum_team_cost_usd REAL NOT NULL,estimated_duration_hours REAL NOT NULL,resource_account_id INTEGER NOT NULL,governance_approval_id INTEGER,reservation_ttl_ms INTEGER NOT NULL,simulation INTEGER NOT NULL,plan_supervisor_id INTEGER,plan_estimated_cost_usd REAL NOT NULL,plan_score REAL NOT NULL,reservation_id INTEGER,continuity_key TEXT NOT NULL,created_at_ms INTEGER NOT NULL,updated_at_ms INTEGER NOT NULL,started_at_ms INTEGER,completed_at_ms INTEGER,failure_reason TEXT NOT NULL);"
    "CREATE TABLE IF NOT EXISTS assignment_capabilities(assignment_id INTEGER NOT NULL,position INTEGER NOT NULL,capability_key TEXT NOT NULL,minimum_proficiency REAL NOT NULL,minimum_reliability REAL NOT NULL,required INTEGER NOT NULL,weight REAL NOT NULL,PRIMARY KEY(assignment_id,position),FOREIGN KEY(assignment_id) REFERENCES work_assignments(id) ON DELETE CASCADE);"
    "CREATE TABLE IF NOT EXISTS assignment_tools(assignment_id INTEGER NOT NULL,position INTEGER NOT NULL,tool_key TEXT NOT NULL,operation TEXT NOT NULL,scope TEXT NOT NULL,required INTEGER NOT NULL,PRIMARY KEY(assignment_id,position),FOREIGN KEY(assignment_id) REFERENCES work_assignments(id) ON DELETE CASCADE);"
    "CREATE TABLE IF NOT EXISTS assignment_excluded_agents(assignment_id INTEGER NOT NULL,agent_id INTEGER NOT NULL,PRIMARY KEY(assignment_id,agent_id),FOREIGN KEY(assignment_id) REFERENCES work_assignments(id) ON DELETE CASCADE);"
    "CREATE TABLE IF NOT EXISTS assignment_constraints(assignment_id INTEGER NOT NULL,key TEXT NOT NULL,value TEXT NOT NULL,PRIMARY KEY(assignment_id,key),FOREIGN KEY(assignment_id) REFERENCES work_assignments(id) ON DELETE CASCADE);"
    "CREATE TABLE IF NOT EXISTS assignment_resource_estimates(assignment_id INTEGER NOT NULL,dimension TEXT NOT NULL,amount REAL NOT NULL,PRIMARY KEY(assignment_id,dimension),FOREIGN KEY(assignment_id) REFERENCES work_assignments(id) ON DELETE CASCADE);"
    "CREATE TABLE IF NOT EXISTS assignment_agents(assignment_id INTEGER NOT NULL,position INTEGER NOT NULL,agent_id INTEGER NOT NULL,PRIMARY KEY(assignment_id,position),FOREIGN KEY(assignment_id) REFERENCES work_assignments(id) ON DELETE CASCADE);"
    "CREATE TABLE IF NOT EXISTS assignment_stages(assignment_id INTEGER NOT NULL,stage_index INTEGER NOT NULL,name TEXT NOT NULL,mode TEXT NOT NULL,PRIMARY KEY(assignment_id,stage_index),FOREIGN KEY(assignment_id) REFERENCES work_assignments(id) ON DELETE CASCADE);"
    "CREATE TABLE IF NOT EXISTS assignment_stage_agents(assignment_id INTEGER NOT NULL,stage_index INTEGER NOT NULL,position INTEGER NOT NULL,agent_id INTEGER NOT NULL,PRIMARY KEY(assignment_id,stage_index,position));"
    "CREATE TABLE IF NOT EXISTS assignment_stage_dependencies(assignment_id INTEGER NOT NULL,stage_index INTEGER NOT NULL,depends_on INTEGER NOT NULL,PRIMARY KEY(assignment_id,stage_index,depends_on));"
    "CREATE TABLE IF NOT EXISTS worker_bindings(id INTEGER PRIMARY KEY,assignment_id INTEGER NOT NULL,job_id INTEGER NOT NULL,agent_id INTEGER NOT NULL,worker_key TEXT NOT NULL,bound_at_ms INTEGER NOT NULL,heartbeat_at_ms INTEGER NOT NULL,expires_at_ms INTEGER NOT NULL,released INTEGER NOT NULL,released_at_ms INTEGER,FOREIGN KEY(assignment_id) REFERENCES work_assignments(id));"
    "CREATE TABLE IF NOT EXISTS agent_performance(id INTEGER PRIMARY KEY,agent_id INTEGER NOT NULL,assignment_id INTEGER NOT NULL,job_id INTEGER NOT NULL,capability_key TEXT NOT NULL,outcome TEXT NOT NULL,quality_score REAL NOT NULL,verification_confidence REAL NOT NULL,duration_ms INTEGER NOT NULL,actual_cost_usd REAL NOT NULL,reason TEXT NOT NULL,created_at_ms INTEGER NOT NULL,FOREIGN KEY(agent_id) REFERENCES agents(id));"
    "CREATE INDEX IF NOT EXISTS idx_agents_live ON agents(status,availability,health,last_heartbeat_at_ms);"
    "CREATE INDEX IF NOT EXISTS idx_agent_capability ON agent_capabilities(capability_key,proficiency,reliability);"
    "CREATE INDEX IF NOT EXISTS idx_assignments_status ON work_assignments(status);"
    "CREATE INDEX IF NOT EXISTS idx_bindings_expiry ON worker_bindings(released,expires_at_ms);"
    "CREATE INDEX IF NOT EXISTS idx_performance_agent ON agent_performance(agent_id,created_at_ms);"
    "INSERT INTO agent_schema_metadata(key,value) VALUES('schema_version','6') ON CONFLICT(key) DO UPDATE SET value=excluded.value;");
}
std::uint64_t SqliteAgentRepository::next_id(std::string_view table){static const std::vector<std::string_view> allowed={"agents","capability_definitions","capability_evidence","agent_performance","work_assignments","worker_bindings"};if(std::find(allowed.begin(),allowed.end(),table)==allowed.end())throw std::invalid_argument("Invalid ID table");return database_.next_sequence("agents."+std::string{table});}
AgentId SqliteAgentRepository::next_agent_id(){return next_id("agents");} CapabilityDefinitionId SqliteAgentRepository::next_capability_definition_id(){return next_id("capability_definitions");} CapabilityEvidenceId SqliteAgentRepository::next_capability_evidence_id(){return next_id("capability_evidence");} PerformanceRecordId SqliteAgentRepository::next_performance_record_id(){return next_id("agent_performance");} AssignmentId SqliteAgentRepository::next_assignment_id(){return next_id("work_assignments");} WorkerBindingId SqliteAgentRepository::next_worker_binding_id(){return next_id("worker_bindings");}

void SqliteAgentRepository::save_agent(const AgentIdentity&a){persistence::Transaction tx{database_};Statement s{database_,"INSERT INTO agents(id,identity_key,display_name,status,availability,health,trust,specialist_title,primary_domain,specialty,description,runtime_kind,runtime_version,model_provider,model_name,model_version,endpoint,maximum_context_tokens,supports_tools,supports_parallel_work,fixed_cost_usd,hourly_cost_usd,input_token_cost,output_token_cost,api_credits_per_task,active_tasks,maximum_tasks,utilization,workload_updated_ms,resource_account_id,registered_at_ms,updated_at_ms,revoked_at_ms,last_heartbeat_at_ms,revocation_reason) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET identity_key=excluded.identity_key,display_name=excluded.display_name,status=excluded.status,availability=excluded.availability,health=excluded.health,trust=excluded.trust,specialist_title=excluded.specialist_title,primary_domain=excluded.primary_domain,specialty=excluded.specialty,description=excluded.description,runtime_kind=excluded.runtime_kind,runtime_version=excluded.runtime_version,model_provider=excluded.model_provider,model_name=excluded.model_name,model_version=excluded.model_version,endpoint=excluded.endpoint,maximum_context_tokens=excluded.maximum_context_tokens,supports_tools=excluded.supports_tools,supports_parallel_work=excluded.supports_parallel_work,fixed_cost_usd=excluded.fixed_cost_usd,hourly_cost_usd=excluded.hourly_cost_usd,input_token_cost=excluded.input_token_cost,output_token_cost=excluded.output_token_cost,api_credits_per_task=excluded.api_credits_per_task,active_tasks=excluded.active_tasks,maximum_tasks=excluded.maximum_tasks,utilization=excluded.utilization,workload_updated_ms=excluded.workload_updated_ms,resource_account_id=excluded.resource_account_id,updated_at_ms=excluded.updated_at_ms,revoked_at_ms=excluded.revoked_at_ms,last_heartbeat_at_ms=excluded.last_heartbeat_at_ms,revocation_reason=excluded.revocation_reason;"};
    std::size_t i=1;s.bind(i++,sid(a.id));s.bind(i++,a.identity_key);s.bind(i++,a.display_name);s.bind(i++,to_string(a.status));s.bind(i++,to_string(a.availability));s.bind(i++,to_string(a.health));s.bind(i++,to_string(a.trust));s.bind(i++,a.specialist.title);s.bind(i++,a.specialist.primary_domain);s.bind(i++,a.specialist.specialty);s.bind(i++,a.specialist.description);s.bind(i++,a.runtime.runtime_kind);s.bind(i++,a.runtime.runtime_version);s.bind(i++,a.runtime.model_provider);s.bind(i++,a.runtime.model_name);s.bind(i++,a.runtime.model_version);s.bind(i++,a.runtime.endpoint);s.bind(i++,sid(a.runtime.maximum_context_tokens));s.bind(i++,static_cast<std::int64_t>(a.runtime.supports_tools));s.bind(i++,static_cast<std::int64_t>(a.runtime.supports_parallel_work));s.bind(i++,a.cost.fixed_cost_usd);s.bind(i++,a.cost.hourly_cost_usd);s.bind(i++,a.cost.input_token_cost_per_million_usd);s.bind(i++,a.cost.output_token_cost_per_million_usd);s.bind(i++,a.cost.api_credits_per_task);s.bind(i++,static_cast<std::int64_t>(a.workload.active_tasks));s.bind(i++,static_cast<std::int64_t>(a.workload.maximum_tasks));s.bind(i++,a.workload.utilization);s.bind(i++,to_unix_milliseconds(a.workload.updated_at));if(a.resource_account_id)s.bind(i++,sid(*a.resource_account_id));else s.bind_null(i++);s.bind(i++,to_unix_milliseconds(a.registered_at));s.bind(i++,to_unix_milliseconds(a.updated_at));bind_optional_time(s,i++,a.revoked_at);bind_optional_time(s,i++,a.last_heartbeat_at);s.bind(i++,a.revocation_reason);s.execute();save_agent_children(a);tx.commit();}
void SqliteAgentRepository::save_agent_children(const AgentIdentity&a){
    for(const auto& table:{"agent_roles","agent_attributes","agent_runtime_attributes","agent_domains","agent_tags"})database_.execute("DELETE FROM "+std::string{table}+" WHERE agent_id="+std::to_string(a.id)+";");
    for(const auto&v:a.roles){Statement s{database_,"INSERT INTO agent_roles(agent_id,role) VALUES(?,?);"};s.bind(1,sid(a.id));s.bind(2,v);s.execute();}
    for(const auto&[k,v]:a.attributes){Statement s{database_,"INSERT INTO agent_attributes(agent_id,key,value) VALUES(?,?,?);"};s.bind(1,sid(a.id));s.bind(2,k);s.bind(3,v);s.execute();}
    for(const auto&[k,v]:a.runtime.attributes){Statement s{database_,"INSERT INTO agent_runtime_attributes(agent_id,key,value) VALUES(?,?,?);"};s.bind(1,sid(a.id));s.bind(2,k);s.bind(3,v);s.execute();}
    for(const auto&v:a.domain_scopes){Statement s{database_,"INSERT INTO agent_domains(agent_id,domain) VALUES(?,?);"};s.bind(1,sid(a.id));s.bind(2,v);s.execute();}
    for(const auto&v:a.specialist.tags){Statement s{database_,"INSERT INTO agent_tags(agent_id,tag) VALUES(?,?);"};s.bind(1,sid(a.id));s.bind(2,v);s.execute();}
}
std::optional<AgentIdentity> SqliteAgentRepository::load_agent(AgentId id){Statement s{database_,"SELECT identity_key,display_name,status,availability,health,trust,specialist_title,primary_domain,specialty,description,runtime_kind,runtime_version,model_provider,model_name,model_version,endpoint,maximum_context_tokens,supports_tools,supports_parallel_work,fixed_cost_usd,hourly_cost_usd,input_token_cost,output_token_cost,api_credits_per_task,active_tasks,maximum_tasks,utilization,workload_updated_ms,resource_account_id,registered_at_ms,updated_at_ms,revoked_at_ms,last_heartbeat_at_ms,revocation_reason FROM agents WHERE id=?;"};s.bind(1,sid(id));if(!s.step())return std::nullopt;auto st=agent_status_from_string(s.column_text(2));auto av=availability_from_string(s.column_text(3));auto h=health_state_from_string(s.column_text(4));auto t=trust_level_from_string(s.column_text(5));if(!st||!av||!h||!t)throw std::runtime_error("Invalid agent enum in database");AgentIdentity a;a.id=id;a.identity_key=s.column_text(0);a.display_name=s.column_text(1);a.status=*st;a.availability=*av;a.health=*h;a.trust=*t;a.specialist.title=s.column_text(6);a.specialist.primary_domain=s.column_text(7);a.specialist.specialty=s.column_text(8);a.specialist.description=s.column_text(9);a.runtime.runtime_kind=s.column_text(10);a.runtime.runtime_version=s.column_text(11);a.runtime.model_provider=s.column_text(12);a.runtime.model_name=s.column_text(13);a.runtime.model_version=s.column_text(14);a.runtime.endpoint=s.column_text(15);a.runtime.maximum_context_tokens=static_cast<std::uint64_t>(s.column_int64(16));a.runtime.supports_tools=s.column_int64(17)!=0;a.runtime.supports_parallel_work=s.column_int64(18)!=0;a.cost.fixed_cost_usd=s.column_double(19);a.cost.hourly_cost_usd=s.column_double(20);a.cost.input_token_cost_per_million_usd=s.column_double(21);a.cost.output_token_cost_per_million_usd=s.column_double(22);a.cost.api_credits_per_task=s.column_double(23);a.workload.active_tasks=static_cast<std::uint32_t>(s.column_int64(24));a.workload.maximum_tasks=static_cast<std::uint32_t>(s.column_int64(25));a.workload.utilization=s.column_double(26);a.workload.updated_at=from_unix_milliseconds(s.column_int64(27));if(!s.column_is_null(28))a.resource_account_id=static_cast<ResourceAccountId>(s.column_int64(28));a.registered_at=from_unix_milliseconds(s.column_int64(29));a.updated_at=from_unix_milliseconds(s.column_int64(30));a.revoked_at=read_optional_time(s,31);a.last_heartbeat_at=read_optional_time(s,32);a.revocation_reason=s.column_text(33);load_agent_children(a);return a;}
void SqliteAgentRepository::load_agent_children(AgentIdentity&a){
    Statement r{database_,"SELECT role FROM agent_roles WHERE agent_id=? ORDER BY role;"};r.bind(1,sid(a.id));while(r.step())a.roles.push_back(r.column_text(0));
    Statement at{database_,"SELECT key,value FROM agent_attributes WHERE agent_id=?;"};at.bind(1,sid(a.id));while(at.step())a.attributes[at.column_text(0)]=at.column_text(1);
    Statement rt{database_,"SELECT key,value FROM agent_runtime_attributes WHERE agent_id=?;"};rt.bind(1,sid(a.id));while(rt.step())a.runtime.attributes[rt.column_text(0)]=rt.column_text(1);
    Statement d{database_,"SELECT domain FROM agent_domains WHERE agent_id=? ORDER BY domain;"};d.bind(1,sid(a.id));while(d.step())a.domain_scopes.push_back(d.column_text(0));
    Statement tg{database_,"SELECT tag FROM agent_tags WHERE agent_id=? ORDER BY tag;"};tg.bind(1,sid(a.id));while(tg.step())a.specialist.tags.push_back(tg.column_text(0));
}
std::optional<AgentIdentity> SqliteAgentRepository::find_agent(std::string_view key){Statement s{database_,"SELECT id FROM agents WHERE identity_key=?;"};s.bind(1,key);return s.step()?load_agent(static_cast<AgentId>(s.column_int64(0))):std::nullopt;}
std::vector<AgentIdentity> SqliteAgentRepository::load_agents(){std::vector<AgentIdentity> out;Statement s{database_,"SELECT id FROM agents ORDER BY id;"};while(s.step())if(auto a=load_agent(static_cast<AgentId>(s.column_int64(0))))out.push_back(std::move(*a));return out;}
std::vector<AgentIdentity> SqliteAgentRepository::load_live_agents(TimePoint cutoff){std::vector<AgentIdentity> out;Statement s{database_,"SELECT id FROM agents WHERE status='active' AND availability!='unavailable' AND health IN('healthy','degraded') AND last_heartbeat_at_ms>=? ORDER BY utilization ASC,id ASC;"};s.bind(1,to_unix_milliseconds(cutoff));while(s.step())if(auto a=load_agent(static_cast<AgentId>(s.column_int64(0))))out.push_back(std::move(*a));return out;}

void SqliteAgentRepository::save_capability_definition(const CapabilityDefinition&d){persistence::Transaction tx{database_};Statement s{database_,"INSERT INTO capability_definitions(id,key,parent_key,domain,name,description,active,created_at_ms) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(key) DO UPDATE SET parent_key=excluded.parent_key,domain=excluded.domain,name=excluded.name,description=excluded.description,active=excluded.active;"};s.bind(1,sid(d.id));s.bind(2,d.key);if(d.parent_key)s.bind(3,*d.parent_key);else s.bind_null(3);s.bind(4,d.domain);s.bind(5,d.name);s.bind(6,d.description);s.bind(7,static_cast<std::int64_t>(d.active));s.bind(8,to_unix_milliseconds(d.created_at));s.execute();database_.execute("DELETE FROM capability_required_tools WHERE capability_id="+std::to_string(d.id)+";");for(const auto&t:d.required_tools){Statement x{database_,"INSERT INTO capability_required_tools(capability_id,tool_key) VALUES(?,?);"};x.bind(1,sid(d.id));x.bind(2,t);x.execute();}tx.commit();}
std::optional<CapabilityDefinition> SqliteAgentRepository::load_capability_definition(std::string_view key){Statement s{database_,"SELECT id,parent_key,domain,name,description,active,created_at_ms FROM capability_definitions WHERE key=?;"};s.bind(1,key);if(!s.step())return std::nullopt;CapabilityDefinition d;d.id=static_cast<CapabilityDefinitionId>(s.column_int64(0));d.key=std::string{key};if(!s.column_is_null(1))d.parent_key=s.column_text(1);d.domain=s.column_text(2);d.name=s.column_text(3);d.description=s.column_text(4);d.active=s.column_int64(5)!=0;d.created_at=from_unix_milliseconds(s.column_int64(6));Statement t{database_,"SELECT tool_key FROM capability_required_tools WHERE capability_id=? ORDER BY tool_key;"};t.bind(1,sid(d.id));while(t.step())d.required_tools.push_back(t.column_text(0));return d;}
std::vector<CapabilityDefinition> SqliteAgentRepository::load_capability_definitions(){std::vector<CapabilityDefinition> out;Statement s{database_,"SELECT key FROM capability_definitions ORDER BY key;"};while(s.step())if(auto d=load_capability_definition(s.column_text(0)))out.push_back(std::move(*d));return out;}
void SqliteAgentRepository::save_agent_capability(const AgentCapability&c){Statement s{database_,"INSERT INTO agent_capabilities(agent_id,capability_key,proficiency,reliability,successful_uses,failed_uses,last_validated_at_ms) VALUES(?,?,?,?,?,?,?) ON CONFLICT(agent_id,capability_key) DO UPDATE SET proficiency=excluded.proficiency,reliability=excluded.reliability,successful_uses=excluded.successful_uses,failed_uses=excluded.failed_uses,last_validated_at_ms=excluded.last_validated_at_ms;"};s.bind(1,sid(c.agent_id));s.bind(2,c.capability_key);s.bind(3,c.proficiency);s.bind(4,c.reliability);s.bind(5,sid(c.successful_uses));s.bind(6,sid(c.failed_uses));s.bind(7,to_unix_milliseconds(c.last_validated_at));s.execute();}
std::vector<AgentCapability> SqliteAgentRepository::load_agent_capabilities(AgentId id){std::vector<AgentCapability> out;Statement s{database_,"SELECT capability_key,proficiency,reliability,successful_uses,failed_uses,last_validated_at_ms FROM agent_capabilities WHERE agent_id=?;"};s.bind(1,sid(id));while(s.step())out.push_back({id,s.column_text(0),s.column_double(1),s.column_double(2),static_cast<std::uint64_t>(s.column_int64(3)),static_cast<std::uint64_t>(s.column_int64(4)),from_unix_milliseconds(s.column_int64(5))});return out;}
std::vector<AgentCapability> SqliteAgentRepository::find_agents_with_capability(std::string_view key){std::vector<AgentCapability> out;Statement s{database_,"SELECT agent_id,proficiency,reliability,successful_uses,failed_uses,last_validated_at_ms FROM agent_capabilities WHERE capability_key=? ORDER BY proficiency DESC,reliability DESC;"};s.bind(1,key);while(s.step())out.push_back({static_cast<AgentId>(s.column_int64(0)),std::string{key},s.column_double(1),s.column_double(2),static_cast<std::uint64_t>(s.column_int64(3)),static_cast<std::uint64_t>(s.column_int64(4)),from_unix_milliseconds(s.column_int64(5))});return out;}

void SqliteAgentRepository::save_tool_permission(const ToolPermission&p){persistence::Transaction tx{database_};Statement s{database_,"INSERT INTO agent_tool_permissions(agent_id,tool_key,scope,allowed,valid_from_ms,valid_until_ms) VALUES(?,?,?,?,?,?) ON CONFLICT(agent_id,tool_key,scope) DO UPDATE SET allowed=excluded.allowed,valid_from_ms=excluded.valid_from_ms,valid_until_ms=excluded.valid_until_ms;"};s.bind(1,sid(p.agent_id));s.bind(2,p.tool_key);s.bind(3,p.scope);s.bind(4,static_cast<std::int64_t>(p.allowed));s.bind(5,to_unix_milliseconds(p.valid_from));bind_optional_time(s,6,p.valid_until);s.execute();Statement del{database_,"DELETE FROM agent_tool_operations WHERE agent_id=? AND tool_key=? AND scope=?;"};del.bind(1,sid(p.agent_id));del.bind(2,p.tool_key);del.bind(3,p.scope);del.execute();for(const auto&o:p.operations){Statement x{database_,"INSERT INTO agent_tool_operations(agent_id,tool_key,scope,operation) VALUES(?,?,?,?);"};x.bind(1,sid(p.agent_id));x.bind(2,p.tool_key);x.bind(3,p.scope);x.bind(4,o);x.execute();}tx.commit();}
std::vector<ToolPermission> SqliteAgentRepository::load_tool_permissions(AgentId id){std::vector<ToolPermission> out;Statement s{database_,"SELECT tool_key,scope,allowed,valid_from_ms,valid_until_ms FROM agent_tool_permissions WHERE agent_id=?;"};s.bind(1,sid(id));while(s.step()){ToolPermission p;p.agent_id=id;p.tool_key=s.column_text(0);p.scope=s.column_text(1);p.allowed=s.column_int64(2)!=0;p.valid_from=from_unix_milliseconds(s.column_int64(3));p.valid_until=read_optional_time(s,4);Statement o{database_,"SELECT operation FROM agent_tool_operations WHERE agent_id=? AND tool_key=? AND scope=?;"};o.bind(1,sid(id));o.bind(2,p.tool_key);o.bind(3,p.scope);while(o.step())p.operations.insert(o.column_text(0));out.push_back(std::move(p));}return out;}
void SqliteAgentRepository::append_capability_evidence(const CapabilityEvidence&e){Statement s{database_,"INSERT INTO capability_evidence(id,agent_id,capability_key,evidence_type,reference,confidence,payload_json,created_at_ms) VALUES(?,?,?,?,?,?,?,?);"};s.bind(1,sid(e.id));s.bind(2,sid(e.agent_id));s.bind(3,e.capability_key);s.bind(4,e.evidence_type);s.bind(5,e.reference);s.bind(6,e.confidence);s.bind(7,e.payload_json);s.bind(8,to_unix_milliseconds(e.created_at));s.execute();}
std::vector<CapabilityEvidence> SqliteAgentRepository::load_capability_evidence(AgentId id,std::string_view key){std::vector<CapabilityEvidence> out;Statement s{database_,"SELECT id,evidence_type,reference,confidence,payload_json,created_at_ms FROM capability_evidence WHERE agent_id=? AND capability_key=? ORDER BY created_at_ms DESC;"};s.bind(1,sid(id));s.bind(2,key);while(s.step())out.push_back({static_cast<CapabilityEvidenceId>(s.column_int64(0)),id,std::string{key},s.column_text(1),s.column_text(2),s.column_double(3),s.column_text(4),from_unix_milliseconds(s.column_int64(5))});return out;}

void SqliteAgentRepository::save_assignment(const WorkAssignment&a){persistence::Transaction tx{database_};Statement s{database_,"INSERT INTO work_assignments(id,version,job_id,proposal_id,status,action,domain,minimum_trust,minimum_team_size,preferred_team_size,maximum_team_size,plan_mode,supervisor_required,supervisor_capability,maximum_team_cost_usd,estimated_duration_hours,resource_account_id,governance_approval_id,reservation_ttl_ms,simulation,plan_supervisor_id,plan_estimated_cost_usd,plan_score,reservation_id,continuity_key,created_at_ms,updated_at_ms,started_at_ms,completed_at_ms,failure_reason) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET version=excluded.version,status=excluded.status,plan_mode=excluded.plan_mode,plan_supervisor_id=excluded.plan_supervisor_id,plan_estimated_cost_usd=excluded.plan_estimated_cost_usd,plan_score=excluded.plan_score,reservation_id=excluded.reservation_id,updated_at_ms=excluded.updated_at_ms,started_at_ms=excluded.started_at_ms,completed_at_ms=excluded.completed_at_ms,failure_reason=excluded.failure_reason;"};std::size_t i=1;s.bind(i++,sid(a.id));s.bind(i++,static_cast<std::int64_t>(a.version));s.bind(i++,sid(a.job_id));s.bind(i++,sid(a.proposal_id));s.bind(i++,to_string(a.status));s.bind(i++,a.requirement.action);s.bind(i++,a.requirement.domain);s.bind(i++,to_string(a.requirement.minimum_trust));s.bind(i++,static_cast<std::int64_t>(a.requirement.minimum_team_size));s.bind(i++,static_cast<std::int64_t>(a.requirement.preferred_team_size));s.bind(i++,static_cast<std::int64_t>(a.requirement.maximum_team_size));s.bind(i++,to_string(a.plan.mode));s.bind(i++,static_cast<std::int64_t>(a.requirement.supervisor_required));if(a.requirement.supervisor_capability)s.bind(i++,*a.requirement.supervisor_capability);else s.bind_null(i++);s.bind(i++,a.requirement.maximum_team_cost_usd);s.bind(i++,a.requirement.estimated_duration_hours);s.bind(i++,sid(a.requirement.resource_account_id));if(a.requirement.governance_approval_id)s.bind(i++,sid(*a.requirement.governance_approval_id));else s.bind_null(i++);s.bind(i++,static_cast<std::int64_t>(a.requirement.reservation_ttl.count()));s.bind(i++,static_cast<std::int64_t>(a.requirement.simulation));if(a.plan.supervisor_id)s.bind(i++,sid(*a.plan.supervisor_id));else s.bind_null(i++);s.bind(i++,a.plan.estimated_cost_usd);s.bind(i++,a.plan.score);if(a.reservation_id)s.bind(i++,sid(*a.reservation_id));else s.bind_null(i++);s.bind(i++,a.continuity_key);s.bind(i++,to_unix_milliseconds(a.created_at));s.bind(i++,to_unix_milliseconds(a.updated_at));bind_optional_time(s,i++,a.started_at);bind_optional_time(s,i++,a.completed_at);s.bind(i++,a.failure_reason);s.execute();save_assignment_children(a);tx.commit();}
void SqliteAgentRepository::save_assignment_children(const WorkAssignment&a){for(const auto&t:{"assignment_capabilities","assignment_tools","assignment_excluded_agents","assignment_constraints","assignment_resource_estimates","assignment_agents","assignment_stages","assignment_stage_agents","assignment_stage_dependencies"})database_.execute("DELETE FROM "+std::string{t}+" WHERE assignment_id="+std::to_string(a.id)+";");
    for(std::size_t i=0;i<a.requirement.capabilities.size();++i){const auto&c=a.requirement.capabilities[i];Statement s{database_,"INSERT INTO assignment_capabilities VALUES(?,?,?,?,?,?,?);"};s.bind(1,sid(a.id));s.bind(2,static_cast<std::int64_t>(i));s.bind(3,c.capability_key);s.bind(4,c.minimum_proficiency);s.bind(5,c.minimum_reliability);s.bind(6,static_cast<std::int64_t>(c.required));s.bind(7,c.weight);s.execute();}
    for(std::size_t i=0;i<a.requirement.tools.size();++i){const auto&t=a.requirement.tools[i];Statement s{database_,"INSERT INTO assignment_tools VALUES(?,?,?,?,?,?);"};s.bind(1,sid(a.id));s.bind(2,static_cast<std::int64_t>(i));s.bind(3,t.tool_key);s.bind(4,t.operation);s.bind(5,t.scope);s.bind(6,static_cast<std::int64_t>(t.required));s.execute();}
    for(auto id:a.requirement.excluded_agents){Statement s{database_,"INSERT INTO assignment_excluded_agents VALUES(?,?);"};s.bind(1,sid(a.id));s.bind(2,sid(id));s.execute();}
    for(const auto&[k,v]:a.requirement.constraints){Statement s{database_,"INSERT INTO assignment_constraints VALUES(?,?,?);"};s.bind(1,sid(a.id));s.bind(2,k);s.bind(3,v);s.execute();}
    for(const auto&[d,v]:a.requirement.resource_estimate.values()){Statement s{database_,"INSERT INTO assignment_resource_estimates VALUES(?,?,?);"};s.bind(1,sid(a.id));s.bind(2,resources::to_string(d));s.bind(3,v);s.execute();}
    for(std::size_t i=0;i<a.plan.agent_ids.size();++i){Statement s{database_,"INSERT INTO assignment_agents VALUES(?,?,?);"};s.bind(1,sid(a.id));s.bind(2,static_cast<std::int64_t>(i));s.bind(3,sid(a.plan.agent_ids[i]));s.execute();}
    for(const auto&st:a.plan.stages){Statement s{database_,"INSERT INTO assignment_stages VALUES(?,?,?,?);"};s.bind(1,sid(a.id));s.bind(2,static_cast<std::int64_t>(st.index));s.bind(3,st.name);s.bind(4,to_string(st.mode));s.execute();for(std::size_t i=0;i<st.agent_ids.size();++i){Statement x{database_,"INSERT INTO assignment_stage_agents VALUES(?,?,?,?);"};x.bind(1,sid(a.id));x.bind(2,static_cast<std::int64_t>(st.index));x.bind(3,static_cast<std::int64_t>(i));x.bind(4,sid(st.agent_ids[i]));x.execute();}for(auto dep:st.depends_on_stages){Statement x{database_,"INSERT INTO assignment_stage_dependencies VALUES(?,?,?);"};x.bind(1,sid(a.id));x.bind(2,static_cast<std::int64_t>(st.index));x.bind(3,static_cast<std::int64_t>(dep));x.execute();}}
}
std::optional<WorkAssignment> SqliteAgentRepository::load_assignment(AssignmentId id){Statement s{database_,"SELECT version,job_id,proposal_id,status,action,domain,minimum_trust,minimum_team_size,preferred_team_size,maximum_team_size,plan_mode,supervisor_required,supervisor_capability,maximum_team_cost_usd,estimated_duration_hours,resource_account_id,governance_approval_id,reservation_ttl_ms,simulation,plan_supervisor_id,plan_estimated_cost_usd,plan_score,reservation_id,continuity_key,created_at_ms,updated_at_ms,started_at_ms,completed_at_ms,failure_reason FROM work_assignments WHERE id=?;"};s.bind(1,sid(id));if(!s.step())return std::nullopt;auto status=assignment_status_from_string(s.column_text(3));auto trust=trust_level_from_string(s.column_text(6));auto mode=work_plan_mode_from_string(s.column_text(10));if(!status||!trust||!mode)throw std::runtime_error("Invalid assignment enum");WorkAssignment a;a.id=id;a.version=static_cast<AssignmentVersion>(s.column_int64(0));a.job_id=static_cast<scheduler::JobId>(s.column_int64(1));a.proposal_id=static_cast<ProposalId>(s.column_int64(2));a.status=*status;a.requirement.job_id=a.job_id;a.requirement.proposal_id=a.proposal_id;a.requirement.action=s.column_text(4);a.requirement.domain=s.column_text(5);a.requirement.minimum_trust=*trust;a.requirement.minimum_team_size=static_cast<std::uint32_t>(s.column_int64(7));a.requirement.preferred_team_size=static_cast<std::uint32_t>(s.column_int64(8));a.requirement.maximum_team_size=static_cast<std::uint32_t>(s.column_int64(9));a.requirement.mode=*mode;a.plan.mode=*mode;a.requirement.supervisor_required=s.column_int64(11)!=0;if(!s.column_is_null(12))a.requirement.supervisor_capability=s.column_text(12);a.requirement.maximum_team_cost_usd=s.column_double(13);a.requirement.estimated_duration_hours=s.column_double(14);a.requirement.resource_account_id=static_cast<ResourceAccountId>(s.column_int64(15));if(!s.column_is_null(16))a.requirement.governance_approval_id=static_cast<GovernanceApprovalId>(s.column_int64(16));a.requirement.reservation_ttl=std::chrono::milliseconds{s.column_int64(17)};a.requirement.simulation=s.column_int64(18)!=0;if(!s.column_is_null(19))a.plan.supervisor_id=static_cast<AgentId>(s.column_int64(19));a.plan.estimated_cost_usd=s.column_double(20);a.plan.score=s.column_double(21);if(!s.column_is_null(22))a.reservation_id=static_cast<resources::ReservationId>(s.column_int64(22));a.continuity_key=s.column_text(23);a.created_at=from_unix_milliseconds(s.column_int64(24));a.updated_at=from_unix_milliseconds(s.column_int64(25));a.started_at=read_optional_time(s,26);a.completed_at=read_optional_time(s,27);a.failure_reason=s.column_text(28);load_assignment_children(a);return a;}
void SqliteAgentRepository::load_assignment_children(WorkAssignment&a){
    Statement c{database_,"SELECT capability_key,minimum_proficiency,minimum_reliability,required,weight FROM assignment_capabilities WHERE assignment_id=? ORDER BY position;"};c.bind(1,sid(a.id));while(c.step())a.requirement.capabilities.push_back({c.column_text(0),c.column_double(1),c.column_double(2),c.column_int64(3)!=0,c.column_double(4)});
    Statement t{database_,"SELECT tool_key,operation,scope,required FROM assignment_tools WHERE assignment_id=? ORDER BY position;"};t.bind(1,sid(a.id));while(t.step())a.requirement.tools.push_back({t.column_text(0),t.column_text(1),t.column_text(2),t.column_int64(3)!=0});
    Statement e{database_,"SELECT agent_id FROM assignment_excluded_agents WHERE assignment_id=?;"};e.bind(1,sid(a.id));while(e.step())a.requirement.excluded_agents.push_back(static_cast<AgentId>(e.column_int64(0)));
    Statement x{database_,"SELECT key,value FROM assignment_constraints WHERE assignment_id=?;"};x.bind(1,sid(a.id));while(x.step())a.requirement.constraints[x.column_text(0)]=x.column_text(1);
    Statement rv{database_,"SELECT dimension,amount FROM assignment_resource_estimates WHERE assignment_id=?;"};rv.bind(1,sid(a.id));while(rv.step()){auto d=resources::resource_dimension_from_string(rv.column_text(0));if(d)a.requirement.resource_estimate.set(*d,rv.column_double(1));}
    Statement ag{database_,"SELECT agent_id FROM assignment_agents WHERE assignment_id=? ORDER BY position;"};ag.bind(1,sid(a.id));while(ag.step())a.plan.agent_ids.push_back(static_cast<AgentId>(ag.column_int64(0)));
    Statement st{database_,"SELECT stage_index,name,mode FROM assignment_stages WHERE assignment_id=? ORDER BY stage_index;"};st.bind(1,sid(a.id));while(st.step()){auto m=work_plan_mode_from_string(st.column_text(2));if(!m)throw std::runtime_error("Invalid stage mode");WorkStage ws;ws.index=static_cast<std::uint32_t>(st.column_int64(0));ws.name=st.column_text(1);ws.mode=*m;Statement sa{database_,"SELECT agent_id FROM assignment_stage_agents WHERE assignment_id=? AND stage_index=? ORDER BY position;"};sa.bind(1,sid(a.id));sa.bind(2,static_cast<std::int64_t>(ws.index));while(sa.step())ws.agent_ids.push_back(static_cast<AgentId>(sa.column_int64(0)));Statement sd{database_,"SELECT depends_on FROM assignment_stage_dependencies WHERE assignment_id=? AND stage_index=? ORDER BY depends_on;"};sd.bind(1,sid(a.id));sd.bind(2,static_cast<std::int64_t>(ws.index));while(sd.step())ws.depends_on_stages.push_back(static_cast<std::uint32_t>(sd.column_int64(0)));a.plan.stages.push_back(std::move(ws));}
}
std::optional<WorkAssignment> SqliteAgentRepository::find_assignment_by_job(scheduler::JobId id){Statement s{database_,"SELECT id FROM work_assignments WHERE job_id=?;"};s.bind(1,sid(id));return s.step()?load_assignment(static_cast<AssignmentId>(s.column_int64(0))):std::nullopt;}
std::vector<WorkAssignment> SqliteAgentRepository::load_active_assignments(){std::vector<WorkAssignment> out;Statement s{database_,"SELECT id FROM work_assignments WHERE status IN('bound','running','replacing','interrupted') ORDER BY id;"};while(s.step())if(auto a=load_assignment(static_cast<AssignmentId>(s.column_int64(0))))out.push_back(std::move(*a));return out;}

void SqliteAgentRepository::save_worker_binding(const WorkerBinding&b){Statement s{database_,"INSERT INTO worker_bindings(id,assignment_id,job_id,agent_id,worker_key,bound_at_ms,heartbeat_at_ms,expires_at_ms,released,released_at_ms) VALUES(?,?,?,?,?,?,?,?,?,NULL) ON CONFLICT(id) DO UPDATE SET heartbeat_at_ms=excluded.heartbeat_at_ms,expires_at_ms=excluded.expires_at_ms,released=excluded.released;"};s.bind(1,sid(b.id));s.bind(2,sid(b.assignment_id));s.bind(3,sid(b.job_id));s.bind(4,sid(b.agent_id));s.bind(5,b.worker_key);s.bind(6,to_unix_milliseconds(b.bound_at));s.bind(7,to_unix_milliseconds(b.heartbeat_at));s.bind(8,to_unix_milliseconds(b.expires_at));s.bind(9,static_cast<std::int64_t>(b.released));s.execute();}
std::optional<WorkerBinding> SqliteAgentRepository::load_binding(WorkerBindingId id){Statement s{database_,"SELECT assignment_id,job_id,agent_id,worker_key,bound_at_ms,heartbeat_at_ms,expires_at_ms,released FROM worker_bindings WHERE id=?;"};s.bind(1,sid(id));if(!s.step())return std::nullopt;return WorkerBinding{id,static_cast<AssignmentId>(s.column_int64(0)),static_cast<scheduler::JobId>(s.column_int64(1)),static_cast<AgentId>(s.column_int64(2)),s.column_text(3),from_unix_milliseconds(s.column_int64(4)),from_unix_milliseconds(s.column_int64(5)),from_unix_milliseconds(s.column_int64(6)),s.column_int64(7)!=0};}
std::vector<WorkerBinding> SqliteAgentRepository::load_active_bindings(){std::vector<WorkerBinding> out;Statement s{database_,"SELECT id FROM worker_bindings WHERE released=0 ORDER BY id;"};while(s.step())if(auto b=load_binding(static_cast<WorkerBindingId>(s.column_int64(0))))out.push_back(*b);return out;}
std::vector<WorkerBinding> SqliteAgentRepository::load_expired_bindings(TimePoint now){std::vector<WorkerBinding> out;Statement s{database_,"SELECT id FROM worker_bindings WHERE released=0 AND expires_at_ms<=? ORDER BY id;"};s.bind(1,to_unix_milliseconds(now));while(s.step())if(auto b=load_binding(static_cast<WorkerBindingId>(s.column_int64(0))))out.push_back(*b);return out;}
bool SqliteAgentRepository::heartbeat_binding(WorkerBindingId id,TimePoint h,TimePoint e){Statement s{database_,"UPDATE worker_bindings SET heartbeat_at_ms=?,expires_at_ms=? WHERE id=? AND released=0;"};s.bind(1,to_unix_milliseconds(h));s.bind(2,to_unix_milliseconds(e));s.bind(3,sid(id));s.execute();return true;}
bool SqliteAgentRepository::release_binding(WorkerBindingId id,TimePoint at){Statement s{database_,"UPDATE worker_bindings SET released=1,released_at_ms=? WHERE id=? AND released=0;"};s.bind(1,to_unix_milliseconds(at));s.bind(2,sid(id));s.execute();return true;}

void SqliteAgentRepository::append_performance_record(const PerformanceRecord&r){Statement s{database_,"INSERT INTO agent_performance(id,agent_id,assignment_id,job_id,capability_key,outcome,quality_score,verification_confidence,duration_ms,actual_cost_usd,reason,created_at_ms) VALUES(?,?,?,?,?,?,?,?,?,?,?,?);"};s.bind(1,sid(r.id));s.bind(2,sid(r.agent_id));s.bind(3,sid(r.assignment_id));s.bind(4,sid(r.job_id));s.bind(5,r.capability_key);s.bind(6,to_string(r.outcome));s.bind(7,r.quality_score);s.bind(8,r.verification_confidence);s.bind(9,static_cast<std::int64_t>(r.duration.count()));s.bind(10,r.actual_cost_usd);s.bind(11,r.reason);s.bind(12,to_unix_milliseconds(r.created_at));s.execute();}
std::vector<PerformanceRecord> SqliteAgentRepository::load_performance_records(AgentId id,std::size_t limit){std::vector<PerformanceRecord> out;Statement s{database_,"SELECT id,assignment_id,job_id,capability_key,outcome,quality_score,verification_confidence,duration_ms,actual_cost_usd,reason,created_at_ms FROM agent_performance WHERE agent_id=? ORDER BY created_at_ms DESC LIMIT ?;"};s.bind(1,sid(id));s.bind(2,static_cast<std::int64_t>(limit));while(s.step()){auto o=performance_outcome_from_string(s.column_text(4));if(!o)throw std::runtime_error("Invalid performance outcome");out.push_back({static_cast<PerformanceRecordId>(s.column_int64(0)),id,static_cast<AssignmentId>(s.column_int64(1)),static_cast<scheduler::JobId>(s.column_int64(2)),s.column_text(3),*o,s.column_double(5),s.column_double(6),std::chrono::milliseconds{s.column_int64(7)},s.column_double(8),s.column_text(9),from_unix_milliseconds(s.column_int64(10))});}return out;}
RegistryStatus SqliteAgentRepository::status(TimePoint cutoff){RegistryStatus r;auto count=[&](std::string sql){Statement s{database_,sql};return s.step()?static_cast<std::uint64_t>(s.column_int64(0)):0;};r.registered=count("SELECT COUNT(*) FROM agents;");r.active=count("SELECT COUNT(*) FROM agents WHERE status='active';");r.available=count("SELECT COUNT(*) FROM agents WHERE status='active' AND availability='available' AND health IN('healthy','degraded') AND last_heartbeat_at_ms>="+std::to_string(to_unix_milliseconds(cutoff))+";");r.unhealthy=count("SELECT COUNT(*) FROM agents WHERE health='unhealthy';");r.revoked=count("SELECT COUNT(*) FROM agents WHERE status='revoked';");r.running_assignments=count("SELECT COUNT(*) FROM work_assignments WHERE status='running';");r.stale_bindings=count("SELECT COUNT(*) FROM worker_bindings WHERE released=0 AND expires_at_ms<="+std::to_string(to_unix_milliseconds(Clock::now()))+";");return r;}

} // namespace exotic::autonomy::agents
