#include "service.hpp"
#include "sha256.hpp"
#include <algorithm>
namespace exotic::autonomy::governance {
GovernanceService::GovernanceService(GovernanceRepository&r):repository_(r),evaluator_(r){}
AuthorityResult GovernanceService::authorize(const AuthorityContext& c){auto result=evaluator_.evaluate(c);if(!result.approval_required)return result;for(auto&r:repository_.load_pending(Clock::now()))if(r.proposal_id==c.proposal_id){result.request_id=r.id;return result;}return result;}
ApprovalRequestId GovernanceService::request_approval(ApprovalRequest r){r.id=repository_.next_request_id();r.status=ApprovalStatus::Pending;repository_.save_request(r);evidence(r.id,"approval.requested",r.requester_id,"{}");return r.id;}
ApprovalStatus GovernanceService::recompute(ApprovalRequest&r){auto ds=repository_.load_decisions(r.id);std::vector<std::string> approvers,roles;std::uint32_t yes=0;for(const auto&d:ds){if(d.vote==Vote::Reject){r.status=ApprovalStatus::Rejected;return r.status;}if(d.vote==Vote::Approve&&std::find(approvers.begin(),approvers.end(),d.approver_id)==approvers.end()){approvers.push_back(d.approver_id);if(!r.require_distinct_roles||std::find(roles.begin(),roles.end(),d.approver_role)==roles.end()){roles.push_back(d.approver_role);++yes;}}}if(yes>=r.required_approvals)r.status=ApprovalStatus::Approved;return r.status;}
ApprovalStatus GovernanceService::decide(ApprovalRequestId id,const Subject&a,Vote v,std::string reason){auto r=repository_.load_request(id);if(!r||r->status!=ApprovalStatus::Pending)return r?r->status:ApprovalStatus::Rejected;if(r->requester_id==a.id){evidence(id,"approval.separation_of_duties_denied",a.id,"{}");return r->status;}ApprovalDecision d;d.id=repository_.next_decision_id();d.request_id=id;d.approver_id=a.id;d.approver_role=a.roles.empty()?"":a.roles.front();d.vote=v;d.reason=std::move(reason);repository_.append_decision(d);auto s=recompute(*r);if(s!=ApprovalStatus::Pending)r->decided_at=Clock::now();repository_.save_request(*r);evidence(id,"approval.decision",a.id,"{\"vote\":\""+to_string(v)+"\"}");return s;}
bool GovernanceService::revoke(ApprovalRequestId id,std::string_view actor,std::string_view reason){auto r=repository_.load_request(id);if(!r)return false;r->status=ApprovalStatus::Revoked;r->decided_at=Clock::now();repository_.save_request(*r);evidence(id,"approval.revoked",std::string(actor),"{\"reason\":\""+std::string(reason)+"\"}");return true;}
std::size_t GovernanceService::expire_requests(TimePoint now){std::size_t n=0;for(auto&r:repository_.load_pending(now))if(r.expires_at<=now){r.status=ApprovalStatus::Expired;r.decided_at=now;repository_.save_request(r);evidence(r.id,"approval.expired","exotic.governance","{}");++n;}return n;}
void GovernanceService::emergency_stop(std::string_view a,std::string_view r){repository_.set_emergency_stop(true,a,r);}void GovernanceService::clear_emergency_stop(std::string_view a,std::string_view r){repository_.set_emergency_stop(false,a,r);}
void GovernanceService::evidence(ApprovalRequestId id,std::string type,std::string actor,std::string payload){auto chain=repository_.load_evidence(id);DecisionEvidence e;e.id=repository_.next_evidence_id();e.request_id=id;e.event_type=std::move(type);e.actor=std::move(actor);e.payload_json=std::move(payload);e.previous_hash=chain.empty()?"":chain.back().hash;e.hash=sha256_hex(e.previous_hash+e.event_type+e.actor+e.payload_json+std::to_string(to_unix_milliseconds(e.created_at)));repository_.append_evidence(e);}
}
