#include "exotic/runtime/service_adapters.hpp"
#include "exotic/runtime/lifecycle.hpp"
#include "exotic/autonomy/scheduler/sqlite_repository.hpp"
#include "exotic/autonomy/scheduler/condition.hpp"
#include <atomic>
#include <cassert>
#include <thread>
namespace {class Bridge final:public exotic::autonomy::scheduler::ExecutionBridge{public:std::atomic<int>calls{0};exotic::autonomy::scheduler::ExecutionResult execute(const exotic::autonomy::scheduler::Job&,std::stop_token)override{++calls;return{true,exotic::autonomy::scheduler::FailureClass::Permanent,"ok"};}};}
int main(){using namespace exotic;auto p=std::filesystem::temp_directory_path()/"exotic-runtime-scheduler-test.db";std::filesystem::remove(p);
std::filesystem::remove(p.string()+"-wal");std::filesystem::remove(p.string()+"-shm");autonomy::scheduler::SqliteSchedulerRepository repo{p};Bridge bridge;autonomy::scheduler::BasicConditionEvaluator conditions;autonomy::scheduler::DurableScheduler scheduler{repo,bridge,conditions};runtime::LifecycleManager life;auto healthy=[](){return runtime::ServiceHealth{"autonomy",runtime::ServiceState::Running,runtime::HealthLevel::Healthy,"ok",{},runtime::Clock::now()};};life.add(std::make_shared<runtime::CallbackService>("autonomy",std::vector<std::string>{},[](){},[](){},[](){},[](){},healthy));for(auto n:{"governance","resources","agents"})life.add(std::make_shared<runtime::CallbackService>(n,std::vector<std::string>{"autonomy"},[](){},[](){},[](){},[](){},[n](){return runtime::ServiceHealth{n,runtime::ServiceState::Running,runtime::HealthLevel::Healthy,"ok",{},runtime::Clock::now()};}));life.add(std::make_shared<runtime::SchedulerService>(scheduler,2));life.recover_all();life.start_all();autonomy::scheduler::Job j;j.name="integration";j.objective_id=1;j.proposal_id=1;j.idempotency_key="integration-1";auto id=scheduler.submit(j);for(int i=0;i<100;++i){auto v=repo.find_job(id);if(v&&v->status==autonomy::scheduler::JobStatus::Completed)break;std::this_thread::sleep_for(std::chrono::milliseconds(20));}auto done=repo.find_job(id);assert(done&&done->status==autonomy::scheduler::JobStatus::Completed&&bridge.calls==1);life.shutdown();std::filesystem::remove(p);std::filesystem::remove(p.string()+"-wal");std::filesystem::remove(p.string()+"-shm");}
