#include "scheduler.hpp"
#include <algorithm>
#include <future>
#include <unordered_set>

namespace exotic::autonomy::scheduler {
DurableScheduler::DurableScheduler(SchedulerRepository& r,ExecutionBridge& e,const ConditionEvaluator& c,SchedulerLimits l):repository_(r),execution_(e),conditions_(c),limits_(l){}
DurableScheduler::~DurableScheduler(){request_stop();join();}
JobId DurableScheduler::submit(Job job){ if(!job.idempotency_key.empty()) if(auto existing=repository_.find_job_by_idempotency_key(job.idempotency_key)) return existing->id; job.id=repository_.next_job_id(); job.created_at=job.updated_at=Clock::now(); if(job.kind==JobKind::Immediate){job.status=JobStatus::Ready;job.next_run_at=job.created_at;} else if(job.kind==JobKind::Scheduled){job.status=JobStatus::Pending;job.next_run_at=job.trigger.run_at;} else {job.status=JobStatus::Pending;if(job.next_run_at==TimePoint{})job.next_run_at=job.created_at;} repository_.upsert_job(job); return job.id;}
EventId DurableScheduler::publish(Event event){event.id=repository_.next_event_id();event.created_at=Clock::now();if(event.available_at==TimePoint{})event.available_at=event.created_at;repository_.append_event(event);return event.id;}
bool DurableScheduler::cancel(JobId id){auto j=repository_.find_job(id);if(!j)return false;if(j->status==JobStatus::Completed||j->status==JobStatus::DeadLettered)return false;j->status=JobStatus::Cancelled;j->updated_at=Clock::now();repository_.upsert_job(*j);return true;}
void DurableScheduler::set_condition_context(ConditionContext c){std::scoped_lock lock{context_mutex_};condition_context_=std::move(c);}
void DurableScheduler::start(std::size_t n,std::string prefix){if(started_.exchange(true))return;recover();for(std::size_t i=0;i<n;++i)workers_.emplace_back([this,id=prefix+"-"+std::to_string(i+1)](std::stop_token st){worker_loop(st,id);});}
void DurableScheduler::request_stop(){for(auto& w:workers_)w.request_stop();}
void DurableScheduler::join(){workers_.clear();started_=false;}
void DurableScheduler::recover(){auto now=Clock::now();for(const auto& lease:repository_.load_expired_leases(now)){if(auto j=repository_.find_job(lease.job_id)){repository_.release_lease(lease.id,lease.worker_id);if(j->status==JobStatus::Leased||j->status==JobStatus::Running){j->status=JobStatus::WaitingRetry;j->last_error="worker lease expired during restart/recovery";j->next_run_at=now;j->updated_at=now;repository_.upsert_job(*j);}}}}
SchedulerStats DurableScheduler::stats(){return repository_.stats();}
void DurableScheduler::process_events(TimePoint now){auto events=repository_.load_available_events(now,100);auto jobs=repository_.load_jobs();for(const auto& e:events){bool matched=false;for(auto& j:jobs){if(j.status==JobStatus::Cancelled||j.status==JobStatus::Completed||j.status==JobStatus::DeadLettered)continue;if(j.trigger.kind==TriggerKind::EventMatch&&j.trigger.event_type==e.type){j.status=JobStatus::Ready;j.next_run_at=now;j.updated_at=now;repository_.upsert_job(j);matched=true;}}if(matched)repository_.mark_event_consumed(e.id,now);}}
bool DurableScheduler::dependencies_satisfied(const Job& job){if(job.dependencies.empty())return true;std::size_t completed=0,successful=0;for(const auto& dep:job.dependencies){auto j=repository_.find_job(dep.depends_on);if(!j)return false;if(j->status==JobStatus::Completed){++completed;++successful;}else if(j->status==JobStatus::DeadLettered||j->status==JobStatus::Cancelled){++completed;}}
 for(const auto& dep:job.dependencies){switch(dep.policy){case DependencyPolicy::AllCompleted:if(completed!=job.dependencies.size())return false;break;case DependencyPolicy::AllSuccessful:if(successful!=job.dependencies.size())return false;break;case DependencyPolicy::AnyCompleted:if(completed==0)return false;break;case DependencyPolicy::AnySuccessful:if(successful==0)return false;break;}}return true;}
bool DurableScheduler::trigger_satisfied(Job& job,TimePoint now){switch(job.trigger.kind){case TriggerKind::None:return job.next_run_at<=now;case TriggerKind::AtTime:return job.trigger.run_at<=now;case TriggerKind::FixedInterval:return job.next_run_at<=now;case TriggerKind::EventMatch:return job.status==JobStatus::Ready;case TriggerKind::Condition:{ConditionContext c;{std::scoped_lock lock{context_mutex_};c=condition_context_;}return conditions_.evaluate(job.trigger.condition_key,job.trigger.condition_expression,c);}}return false;}
bool DurableScheduler::concurrency_available(const Job& job){auto jobs=repository_.load_jobs();std::uint32_t group=0,global=0;for(const auto& j:jobs){if(j.status==JobStatus::Running||j.status==JobStatus::Leased){++global;if(j.concurrency.group==job.concurrency.group)++group;}}return global<limits_.global_max_running&&group<job.concurrency.max_running;}
void DurableScheduler::complete(Job& job,TimePoint now){job.last_error.clear();if(job.kind==JobKind::Recurring&&job.trigger.interval.count()>0){job.status=JobStatus::Pending;job.attempt=0;job.next_run_at=now+job.trigger.interval;}else{job.status=JobStatus::Completed;job.completed_at=now;}job.updated_at=now;repository_.upsert_job(job);}
void DurableScheduler::dead_letter(Job& job,FailureClass f,std::string reason,TimePoint now){job.status=JobStatus::DeadLettered;job.last_error=reason;job.updated_at=now;repository_.upsert_job(job);DeadLetter d;d.id=repository_.next_dead_letter_id();d.job_id=job.id;d.failure_class=f;d.reason=std::move(reason);d.payload_json=job.payload_json;d.attempts=job.attempt;d.created_at=now;repository_.append_dead_letter(d);}
void DurableScheduler::fail(Job& job,FailureClass f,std::string reason,TimePoint now){job.last_error=reason;if(f!=FailureClass::Transient&&f!=FailureClass::Timeout){dead_letter(job,f,std::move(reason),now);return;}if(job.attempt>=job.retry.max_attempts){dead_letter(job,f,"retry budget exhausted: "+reason,now);return;}job.status=JobStatus::WaitingRetry;job.next_run_at=now+retry_.next_delay(job.retry,job.attempt);job.updated_at=now;repository_.upsert_job(job);}
bool DurableScheduler::try_run(Job job,std::string_view worker,std::stop_token stop){auto now=Clock::now();Lease lease;lease.id=repository_.next_lease_id();lease.job_id=job.id;lease.worker_id=std::string(worker);lease.acquired_at=lease.heartbeat_at=now;lease.expires_at=now+limits_.lease_duration;if(!repository_.try_acquire_lease(lease))return false;auto latest=repository_.find_job(job.id);if(!latest||latest->status==JobStatus::Completed||latest->status==JobStatus::Cancelled||latest->status==JobStatus::DeadLettered||latest->next_run_at>Clock::now()){repository_.release_lease(lease.id,worker);return false;}job=*latest;job.status=JobStatus::Running;job.attempt++;job.updated_at=now;repository_.upsert_job(job);
 std::promise<ExecutionResult> promise;auto future=promise.get_future();std::jthread execution_thread([&](std::stop_token inner){try{promise.set_value(execution_.execute(job,inner));}catch(const std::exception& e){promise.set_value({false,FailureClass::Permanent,e.what()});}catch(...){promise.set_value({false,FailureClass::Permanent,"unknown executor failure"});}});
 const auto deadline=job.deadline.value_or(now+limits_.execution_timeout);auto next_heartbeat=now+limits_.heartbeat_interval;while(future.wait_for(std::chrono::milliseconds{50})!=std::future_status::ready){auto current=Clock::now();if(stop.stop_requested()){execution_thread.request_stop();break;}if(current>=deadline){execution_thread.request_stop();break;}if(current>=next_heartbeat){repository_.heartbeat_lease(lease.id,worker,current,current+limits_.lease_duration);next_heartbeat=current+limits_.heartbeat_interval;}}
 ExecutionResult result;if(stop.stop_requested())result={false,FailureClass::Cancelled,"scheduler shutdown"};else if(Clock::now()>=deadline)result={false,FailureClass::Timeout,"execution timeout"};else result=future.get();execution_thread.request_stop();auto finished=Clock::now();if(result.success)complete(job,finished);else fail(job,result.failure_class,result.message,finished);repository_.release_lease(lease.id,worker);return true;}
void DurableScheduler::tick_once(std::string_view worker){auto now=Clock::now();process_events(now);for(auto job:repository_.load_due_jobs(now,100)){if(job.status==JobStatus::Cancelled||job.status==JobStatus::Completed||job.status==JobStatus::DeadLettered)continue;if(job.deadline&&now>*job.deadline){dead_letter(job,FailureClass::Timeout,"job deadline expired before execution",now);continue;}if(!dependencies_satisfied(job)){job.status=JobStatus::Blocked;job.updated_at=now;repository_.upsert_job(job);continue;}if(!trigger_satisfied(job,now))continue;if(!concurrency_available(job))continue;if(try_run(job,worker,{}))break;}}
void DurableScheduler::worker_loop(std::stop_token stop,std::string id){while(!stop.stop_requested()){tick_once(id);std::this_thread::sleep_for(limits_.poll_interval);}}
} // namespace exotic::autonomy::scheduler
