#include "sqlite_repository.hpp"
#include "../persistence/transaction.hpp"
#include <algorithm>
#include <array>
#include <limits>

namespace exotic::autonomy::scheduler {
using persistence::DatabaseError; using persistence::Statement; using persistence::Transaction;
namespace {
std::int64_t i64(std::uint64_t v){ if(v>static_cast<std::uint64_t>(std::numeric_limits<std::int64_t>::max())) throw DatabaseError("scheduler id overflow"); return static_cast<std::int64_t>(v); }
std::optional<TimePoint> maybe_time(const Statement& s,int c){ if(s.column_is_null(c)) return std::nullopt; return from_unix_milliseconds(s.column_int64(c)); }
}
SqliteSchedulerRepository::SqliteSchedulerRepository(const std::filesystem::path& p):database_(p){migrate();}
void SqliteSchedulerRepository::migrate(){
 Transaction tx{database_};
 database_.execute(R"SQL(
CREATE TABLE IF NOT EXISTS scheduler_jobs(
 id INTEGER PRIMARY KEY, objective_id INTEGER NOT NULL, proposal_id INTEGER NOT NULL,
 name TEXT NOT NULL, payload_json TEXT NOT NULL, idempotency_key TEXT NOT NULL UNIQUE,
 kind TEXT NOT NULL, status TEXT NOT NULL, priority INTEGER NOT NULL,
 trigger_kind TEXT NOT NULL, run_at_ms INTEGER, interval_ms INTEGER NOT NULL,
 event_type TEXT NOT NULL, condition_key TEXT NOT NULL, condition_expression TEXT NOT NULL,
 retry_max_attempts INTEGER NOT NULL, retry_initial_delay_ms INTEGER NOT NULL,
 retry_maximum_delay_ms INTEGER NOT NULL, retry_multiplier REAL NOT NULL,
 retry_jitter_fraction REAL NOT NULL, concurrency_group TEXT NOT NULL,
 concurrency_max_running INTEGER NOT NULL, attempt INTEGER NOT NULL,
 created_at_ms INTEGER NOT NULL, updated_at_ms INTEGER NOT NULL, next_run_at_ms INTEGER NOT NULL,
 deadline_ms INTEGER, completed_at_ms INTEGER, last_error TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS scheduler_job_dependencies(
 job_id INTEGER NOT NULL, depends_on INTEGER NOT NULL, policy TEXT NOT NULL,
 PRIMARY KEY(job_id,depends_on), FOREIGN KEY(job_id) REFERENCES scheduler_jobs(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS scheduler_events(
 id INTEGER PRIMARY KEY, type TEXT NOT NULL, source TEXT NOT NULL, subject TEXT NOT NULL,
 payload_json TEXT NOT NULL, idempotency_key TEXT NOT NULL UNIQUE,
 available_at_ms INTEGER NOT NULL, created_at_ms INTEGER NOT NULL, consumed_at_ms INTEGER
);
CREATE TABLE IF NOT EXISTS scheduler_leases(
 id INTEGER PRIMARY KEY, job_id INTEGER NOT NULL UNIQUE, worker_id TEXT NOT NULL,
 acquired_at_ms INTEGER NOT NULL, heartbeat_at_ms INTEGER NOT NULL,
 expires_at_ms INTEGER NOT NULL, released INTEGER NOT NULL DEFAULT 0,
 FOREIGN KEY(job_id) REFERENCES scheduler_jobs(id)
);
CREATE TABLE IF NOT EXISTS scheduler_dead_letters(
 id INTEGER PRIMARY KEY, job_id INTEGER NOT NULL, failure_class TEXT NOT NULL,
 reason TEXT NOT NULL, payload_json TEXT NOT NULL, attempts INTEGER NOT NULL,
 created_at_ms INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_scheduler_jobs_due ON scheduler_jobs(status,next_run_at_ms,priority);
CREATE INDEX IF NOT EXISTS idx_scheduler_jobs_group ON scheduler_jobs(concurrency_group,status);
CREATE INDEX IF NOT EXISTS idx_scheduler_events_available ON scheduler_events(consumed_at_ms,available_at_ms);
CREATE INDEX IF NOT EXISTS idx_scheduler_leases_expiry ON scheduler_leases(released,expires_at_ms);
)SQL"); tx.commit(); }
std::uint64_t SqliteSchedulerRepository::next_id(std::string_view table){ static constexpr std::array<std::string_view,4> ok{"scheduler_jobs","scheduler_events","scheduler_leases","scheduler_dead_letters"}; if(std::find(ok.begin(),ok.end(),table)==ok.end()) throw DatabaseError("invalid scheduler id table"); return database_.next_sequence("scheduler."+std::string{table}); }
JobId SqliteSchedulerRepository::next_job_id(){return next_id("scheduler_jobs");} EventId SqliteSchedulerRepository::next_event_id(){return next_id("scheduler_events");} LeaseId SqliteSchedulerRepository::next_lease_id(){return next_id("scheduler_leases");} DeadLetterId SqliteSchedulerRepository::next_dead_letter_id(){return next_id("scheduler_dead_letters");}
void SqliteSchedulerRepository::upsert_job(const Job& j){ Transaction tx{database_}; Statement s{database_,R"SQL(
INSERT INTO scheduler_jobs(id,objective_id,proposal_id,name,payload_json,idempotency_key,kind,status,priority,trigger_kind,run_at_ms,interval_ms,event_type,condition_key,condition_expression,retry_max_attempts,retry_initial_delay_ms,retry_maximum_delay_ms,retry_multiplier,retry_jitter_fraction,concurrency_group,concurrency_max_running,attempt,created_at_ms,updated_at_ms,next_run_at_ms,deadline_ms,completed_at_ms,last_error)
VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
ON CONFLICT(id) DO UPDATE SET objective_id=excluded.objective_id,proposal_id=excluded.proposal_id,name=excluded.name,payload_json=excluded.payload_json,idempotency_key=excluded.idempotency_key,kind=excluded.kind,status=excluded.status,priority=excluded.priority,trigger_kind=excluded.trigger_kind,run_at_ms=excluded.run_at_ms,interval_ms=excluded.interval_ms,event_type=excluded.event_type,condition_key=excluded.condition_key,condition_expression=excluded.condition_expression,retry_max_attempts=excluded.retry_max_attempts,retry_initial_delay_ms=excluded.retry_initial_delay_ms,retry_maximum_delay_ms=excluded.retry_maximum_delay_ms,retry_multiplier=excluded.retry_multiplier,retry_jitter_fraction=excluded.retry_jitter_fraction,concurrency_group=excluded.concurrency_group,concurrency_max_running=excluded.concurrency_max_running,attempt=excluded.attempt,updated_at_ms=excluded.updated_at_ms,next_run_at_ms=excluded.next_run_at_ms,deadline_ms=excluded.deadline_ms,completed_at_ms=excluded.completed_at_ms,last_error=excluded.last_error;
)SQL"};
 int n=1; s.bind(n++,i64(j.id)); s.bind(n++,i64(j.objective_id)); s.bind(n++,i64(j.proposal_id)); s.bind(n++,j.name); s.bind(n++,j.payload_json); s.bind(n++,j.idempotency_key); s.bind(n++,to_string(j.kind)); s.bind(n++,to_string(j.status)); s.bind(n++,static_cast<std::int64_t>(j.priority)); s.bind(n++,to_string(j.trigger.kind));
 if(j.trigger.run_at==TimePoint{}) s.bind_null(n++); else s.bind(n++,to_unix_milliseconds(j.trigger.run_at)); s.bind(n++,static_cast<std::int64_t>(j.trigger.interval.count())); s.bind(n++,j.trigger.event_type); s.bind(n++,j.trigger.condition_key); s.bind(n++,j.trigger.condition_expression); s.bind(n++,static_cast<std::int64_t>(j.retry.max_attempts)); s.bind(n++,static_cast<std::int64_t>(j.retry.initial_delay.count())); s.bind(n++,static_cast<std::int64_t>(j.retry.maximum_delay.count())); s.bind(n++,j.retry.multiplier); s.bind(n++,j.retry.jitter_fraction); s.bind(n++,j.concurrency.group); s.bind(n++,static_cast<std::int64_t>(j.concurrency.max_running)); s.bind(n++,static_cast<std::int64_t>(j.attempt)); s.bind(n++,to_unix_milliseconds(j.created_at)); s.bind(n++,to_unix_milliseconds(j.updated_at)); s.bind(n++,to_unix_milliseconds(j.next_run_at)); if(j.deadline) s.bind(n++,to_unix_milliseconds(*j.deadline)); else s.bind_null(n++); if(j.completed_at) s.bind(n++,to_unix_milliseconds(*j.completed_at)); else s.bind_null(n++); s.bind(n++,j.last_error); s.execute(); replace_dependencies(j); tx.commit(); }
void SqliteSchedulerRepository::replace_dependencies(const Job& j){ Statement d{database_,"DELETE FROM scheduler_job_dependencies WHERE job_id=?;"}; d.bind(1,i64(j.id)); d.execute(); for(const auto& dep:j.dependencies){ Statement x{database_,"INSERT INTO scheduler_job_dependencies(job_id,depends_on,policy) VALUES(?,?,?);"}; x.bind(1,i64(j.id)); x.bind(2,i64(dep.depends_on)); x.bind(3,to_string(dep.policy)); x.execute(); }}
std::optional<Job> SqliteSchedulerRepository::load_job_from_id(JobId id){ Statement s{database_,R"SQL(SELECT objective_id,proposal_id,name,payload_json,idempotency_key,kind,status,priority,trigger_kind,run_at_ms,interval_ms,event_type,condition_key,condition_expression,retry_max_attempts,retry_initial_delay_ms,retry_maximum_delay_ms,retry_multiplier,retry_jitter_fraction,concurrency_group,concurrency_max_running,attempt,created_at_ms,updated_at_ms,next_run_at_ms,deadline_ms,completed_at_ms,last_error FROM scheduler_jobs WHERE id=?;)SQL"}; s.bind(1,i64(id)); if(!s.step()) return std::nullopt; auto kind=job_kind_from_string(s.column_text(5)); auto status=job_status_from_string(s.column_text(6)); auto tk=trigger_kind_from_string(s.column_text(8)); if(!kind||!status||!tk) throw DatabaseError("invalid scheduler enum"); Job j; j.id=id; j.objective_id=static_cast<ObjectiveId>(s.column_int64(0)); j.proposal_id=static_cast<ProposalId>(s.column_int64(1)); j.name=s.column_text(2); j.payload_json=s.column_text(3); j.idempotency_key=s.column_text(4); j.kind=*kind; j.status=*status; j.priority=static_cast<JobPriority>(s.column_int64(7)); j.trigger.kind=*tk; if(auto t=maybe_time(s,9)) j.trigger.run_at=*t; j.trigger.interval=std::chrono::milliseconds{s.column_int64(10)}; j.trigger.event_type=s.column_text(11); j.trigger.condition_key=s.column_text(12); j.trigger.condition_expression=s.column_text(13); j.retry.max_attempts=static_cast<std::uint32_t>(s.column_int64(14)); j.retry.initial_delay=std::chrono::milliseconds{s.column_int64(15)}; j.retry.maximum_delay=std::chrono::milliseconds{s.column_int64(16)}; j.retry.multiplier=s.column_double(17); j.retry.jitter_fraction=s.column_double(18); j.concurrency.group=s.column_text(19); j.concurrency.max_running=static_cast<std::uint32_t>(s.column_int64(20)); j.attempt=static_cast<std::uint32_t>(s.column_int64(21)); j.created_at=from_unix_milliseconds(s.column_int64(22)); j.updated_at=from_unix_milliseconds(s.column_int64(23)); j.next_run_at=from_unix_milliseconds(s.column_int64(24)); j.deadline=maybe_time(s,25); j.completed_at=maybe_time(s,26); j.last_error=s.column_text(27); Statement d{database_,"SELECT depends_on,policy FROM scheduler_job_dependencies WHERE job_id=? ORDER BY depends_on;"}; d.bind(1,i64(id)); while(d.step()){ auto p=dependency_policy_from_string(d.column_text(1)); if(!p) throw DatabaseError("invalid dependency policy"); j.dependencies.push_back({static_cast<JobId>(d.column_int64(0)),*p}); } return j; }
std::optional<Job> SqliteSchedulerRepository::find_job(JobId id){return load_job_from_id(id);} std::optional<Job> SqliteSchedulerRepository::find_job_by_idempotency_key(std::string_view key){Statement s{database_,"SELECT id FROM scheduler_jobs WHERE idempotency_key=?;"}; s.bind(1,key); return s.step()?load_job_from_id(static_cast<JobId>(s.column_int64(0))):std::nullopt;}
std::vector<Job> SqliteSchedulerRepository::load_jobs(){std::vector<Job> out; Statement s{database_,"SELECT id FROM scheduler_jobs ORDER BY id;"}; while(s.step()) if(auto j=load_job_from_id(static_cast<JobId>(s.column_int64(0)))) out.push_back(std::move(*j)); return out;}
std::vector<Job> SqliteSchedulerRepository::load_due_jobs(TimePoint now,std::size_t limit){std::vector<Job> out; Statement s{database_,"SELECT id FROM scheduler_jobs WHERE status IN ('pending','ready','waiting_retry','blocked') AND next_run_at_ms<=? ORDER BY priority DESC,next_run_at_ms ASC,id ASC LIMIT ?;"}; s.bind(1,to_unix_milliseconds(now)); s.bind(2,static_cast<std::int64_t>(limit)); while(s.step()) if(auto j=load_job_from_id(static_cast<JobId>(s.column_int64(0)))) out.push_back(std::move(*j)); return out;}
void SqliteSchedulerRepository::append_event(const Event& e){Statement s{database_,"INSERT OR IGNORE INTO scheduler_events(id,type,source,subject,payload_json,idempotency_key,available_at_ms,created_at_ms,consumed_at_ms) VALUES(?,?,?,?,?,?,?,?,?);"}; s.bind(1,i64(e.id)); s.bind(2,e.type); s.bind(3,e.source); s.bind(4,e.subject); s.bind(5,e.payload_json); s.bind(6,e.idempotency_key); s.bind(7,to_unix_milliseconds(e.available_at)); s.bind(8,to_unix_milliseconds(e.created_at)); if(e.consumed_at)s.bind(9,to_unix_milliseconds(*e.consumed_at));else s.bind_null(9); s.execute();}
std::vector<Event> SqliteSchedulerRepository::load_available_events(TimePoint now,std::size_t limit){std::vector<Event> out;Statement s{database_,"SELECT id,type,source,subject,payload_json,idempotency_key,available_at_ms,created_at_ms FROM scheduler_events WHERE consumed_at_ms IS NULL AND available_at_ms<=? ORDER BY available_at_ms,id LIMIT ?;"};s.bind(1,to_unix_milliseconds(now));s.bind(2,static_cast<std::int64_t>(limit));while(s.step()){Event e;e.id=static_cast<EventId>(s.column_int64(0));e.type=s.column_text(1);e.source=s.column_text(2);e.subject=s.column_text(3);e.payload_json=s.column_text(4);e.idempotency_key=s.column_text(5);e.available_at=from_unix_milliseconds(s.column_int64(6));e.created_at=from_unix_milliseconds(s.column_int64(7));out.push_back(std::move(e));}return out;}
void SqliteSchedulerRepository::mark_event_consumed(EventId id,TimePoint t){Statement s{database_,"UPDATE scheduler_events SET consumed_at_ms=? WHERE id=? AND consumed_at_ms IS NULL;"};s.bind(1,to_unix_milliseconds(t));s.bind(2,i64(id));s.execute();}
bool SqliteSchedulerRepository::try_acquire_lease(const Lease& l){Transaction tx{database_}; Statement del{database_,"DELETE FROM scheduler_leases WHERE job_id=? AND (released=1 OR expires_at_ms<=?);"}; del.bind(1,i64(l.job_id));del.bind(2,to_unix_milliseconds(l.acquired_at));del.execute(); Statement s{database_,"INSERT OR IGNORE INTO scheduler_leases(id,job_id,worker_id,acquired_at_ms,heartbeat_at_ms,expires_at_ms,released) VALUES(?,?,?,?,?,?,0);"};s.bind(1,i64(l.id));s.bind(2,i64(l.job_id));s.bind(3,l.worker_id);s.bind(4,to_unix_milliseconds(l.acquired_at));s.bind(5,to_unix_milliseconds(l.heartbeat_at));s.bind(6,to_unix_milliseconds(l.expires_at));s.execute(); Statement q{database_,"SELECT COUNT(*) FROM scheduler_leases WHERE id=? AND worker_id=? AND released=0;"};q.bind(1,i64(l.id));q.bind(2,l.worker_id);bool ok=q.step()&&q.column_int64(0)==1;tx.commit();return ok;}
bool SqliteSchedulerRepository::heartbeat_lease(LeaseId id,std::string_view worker,TimePoint h,TimePoint e){Statement s{database_,"UPDATE scheduler_leases SET heartbeat_at_ms=?,expires_at_ms=? WHERE id=? AND worker_id=? AND released=0;"};s.bind(1,to_unix_milliseconds(h));s.bind(2,to_unix_milliseconds(e));s.bind(3,i64(id));s.bind(4,worker);s.execute();Statement q{database_,"SELECT COUNT(*) FROM scheduler_leases WHERE id=? AND worker_id=? AND released=0 AND expires_at_ms=?;"};q.bind(1,i64(id));q.bind(2,worker);q.bind(3,to_unix_milliseconds(e));return q.step()&&q.column_int64(0)==1;}
bool SqliteSchedulerRepository::release_lease(LeaseId id,std::string_view worker){Statement s{database_,"UPDATE scheduler_leases SET released=1 WHERE id=? AND worker_id=? AND released=0;"};s.bind(1,i64(id));s.bind(2,worker);s.execute();Statement q{database_,"SELECT released FROM scheduler_leases WHERE id=?;"};q.bind(1,i64(id));return q.step()&&q.column_int64(0)==1;}
std::optional<Lease> SqliteSchedulerRepository::find_active_lease_for_job(JobId id){Statement s{database_,"SELECT id,worker_id,acquired_at_ms,heartbeat_at_ms,expires_at_ms,released FROM scheduler_leases WHERE job_id=? AND released=0 ORDER BY id DESC LIMIT 1;"};s.bind(1,i64(id));if(!s.step())return std::nullopt;Lease l;l.id=static_cast<LeaseId>(s.column_int64(0));l.job_id=id;l.worker_id=s.column_text(1);l.acquired_at=from_unix_milliseconds(s.column_int64(2));l.heartbeat_at=from_unix_milliseconds(s.column_int64(3));l.expires_at=from_unix_milliseconds(s.column_int64(4));l.released=s.column_int64(5)!=0;return l;}
std::vector<Lease> SqliteSchedulerRepository::load_expired_leases(TimePoint now){std::vector<Lease>out;Statement s{database_,"SELECT id,job_id,worker_id,acquired_at_ms,heartbeat_at_ms,expires_at_ms FROM scheduler_leases WHERE released=0 AND expires_at_ms<=?;"};s.bind(1,to_unix_milliseconds(now));while(s.step()){Lease l;l.id=static_cast<LeaseId>(s.column_int64(0));l.job_id=static_cast<JobId>(s.column_int64(1));l.worker_id=s.column_text(2);l.acquired_at=from_unix_milliseconds(s.column_int64(3));l.heartbeat_at=from_unix_milliseconds(s.column_int64(4));l.expires_at=from_unix_milliseconds(s.column_int64(5));out.push_back(std::move(l));}return out;}
void SqliteSchedulerRepository::append_dead_letter(const DeadLetter& d){Statement s{database_,"INSERT INTO scheduler_dead_letters(id,job_id,failure_class,reason,payload_json,attempts,created_at_ms) VALUES(?,?,?,?,?,?,?);"};s.bind(1,i64(d.id));s.bind(2,i64(d.job_id));s.bind(3,to_string(d.failure_class));s.bind(4,d.reason);s.bind(5,d.payload_json);s.bind(6,static_cast<std::int64_t>(d.attempts));s.bind(7,to_unix_milliseconds(d.created_at));s.execute();}
std::vector<DeadLetter> SqliteSchedulerRepository::load_dead_letters(std::size_t limit){std::vector<DeadLetter>out;Statement s{database_,"SELECT id,job_id,failure_class,reason,payload_json,attempts,created_at_ms FROM scheduler_dead_letters ORDER BY id DESC LIMIT ?;"};s.bind(1,static_cast<std::int64_t>(limit));while(s.step()){auto f=failure_class_from_string(s.column_text(2));if(!f)throw DatabaseError("invalid dead-letter class");DeadLetter d;d.id=static_cast<DeadLetterId>(s.column_int64(0));d.job_id=static_cast<JobId>(s.column_int64(1));d.failure_class=*f;d.reason=s.column_text(3);d.payload_json=s.column_text(4);d.attempts=static_cast<std::uint32_t>(s.column_int64(5));d.created_at=from_unix_milliseconds(s.column_int64(6));out.push_back(std::move(d));}return out;}
SchedulerStats SqliteSchedulerRepository::stats(){SchedulerStats x;Statement s{database_,"SELECT status,COUNT(*) FROM scheduler_jobs GROUP BY status;"};while(s.step()){auto st=job_status_from_string(s.column_text(0));if(!st)continue;auto n=static_cast<std::uint64_t>(s.column_int64(1));switch(*st){case JobStatus::Pending:x.pending=n;break;case JobStatus::Ready:x.ready=n;break;case JobStatus::Leased:x.leased=n;break;case JobStatus::Running:x.running=n;break;case JobStatus::WaitingRetry:x.waiting_retry=n;break;case JobStatus::Blocked:x.blocked=n;break;case JobStatus::Completed:x.completed=n;break;case JobStatus::DeadLettered:x.dead_lettered=n;break;case JobStatus::Cancelled:break;}}Statement l{database_,"SELECT COUNT(*) FROM scheduler_leases WHERE released=0;"};if(l.step())x.active_leases=static_cast<std::uint64_t>(l.column_int64(0));return x;}
} // namespace exotic::autonomy::scheduler
