#include "sqlite_telemetry.hpp"
#include <limits>
#include <stdexcept>
namespace exotic::runtime {using autonomy::persistence::Statement;
namespace {std::int64_t ms(TimePoint t){return autonomy::to_unix_milliseconds(t);}TimePoint tp(std::int64_t v){return autonomy::from_unix_milliseconds(v);}std::int64_t id64(std::uint64_t v){if(v>static_cast<std::uint64_t>(std::numeric_limits<std::int64_t>::max()))throw std::overflow_error("runtime id overflow");return static_cast<std::int64_t>(v);}ServiceState state(std::string_view v){if(v=="running")return ServiceState::Running;if(v=="recovering")return ServiceState::Recovering;if(v=="starting")return ServiceState::Starting;if(v=="stopping")return ServiceState::Stopping;if(v=="stopped")return ServiceState::Stopped;if(v=="failed")return ServiceState::Failed;return ServiceState::Registered;}HealthLevel level(std::string_view v){if(v=="healthy")return HealthLevel::Healthy;if(v=="degraded")return HealthLevel::Degraded;if(v=="unhealthy")return HealthLevel::Unhealthy;return HealthLevel::Unknown;}AlertSeverity severity(std::string_view v){if(v=="info")return AlertSeverity::Info;if(v=="error")return AlertSeverity::Error;if(v=="critical")return AlertSeverity::Critical;return AlertSeverity::Warning;}}
SqliteTelemetryRepository::SqliteTelemetryRepository(const std::filesystem::path&p,std::string w):db_(p),workspace_id_(std::move(w)){migrate();}
void SqliteTelemetryRepository::migrate(){db_.execute("CREATE TABLE IF NOT EXISTS runtime_schema_metadata(key TEXT PRIMARY KEY,value TEXT NOT NULL);CREATE TABLE IF NOT EXISTS runtime_audit(id INTEGER PRIMARY KEY,workspace_id TEXT NOT NULL,category TEXT NOT NULL,actor TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT NOT NULL,message TEXT NOT NULL,payload_json TEXT NOT NULL,created_at_ms INTEGER NOT NULL);CREATE INDEX IF NOT EXISTS idx_runtime_audit_time ON runtime_audit(workspace_id,created_at_ms);CREATE TABLE IF NOT EXISTS runtime_traces(span_id TEXT PRIMARY KEY,trace_id TEXT NOT NULL,parent_span_id TEXT,workspace_id TEXT NOT NULL,service TEXT NOT NULL,operation TEXT NOT NULL,status TEXT NOT NULL,attributes_json TEXT NOT NULL,started_at_ms INTEGER NOT NULL,ended_at_ms INTEGER);CREATE INDEX IF NOT EXISTS idx_runtime_trace ON runtime_traces(workspace_id,trace_id);CREATE TABLE IF NOT EXISTS runtime_metrics(id INTEGER PRIMARY KEY AUTOINCREMENT,workspace_id TEXT NOT NULL,name TEXT NOT NULL,value REAL NOT NULL,unit TEXT NOT NULL,labels_json TEXT NOT NULL,created_at_ms INTEGER NOT NULL);CREATE INDEX IF NOT EXISTS idx_runtime_metrics ON runtime_metrics(workspace_id,name,created_at_ms);CREATE TABLE IF NOT EXISTS runtime_alerts(id INTEGER PRIMARY KEY,workspace_id TEXT NOT NULL,severity TEXT NOT NULL,source TEXT NOT NULL,code TEXT NOT NULL,message TEXT NOT NULL,details_json TEXT NOT NULL,active INTEGER NOT NULL,created_at_ms INTEGER NOT NULL,acknowledged_at_ms INTEGER);CREATE TABLE IF NOT EXISTS runtime_service_health(workspace_id TEXT NOT NULL,service TEXT NOT NULL,state TEXT NOT NULL,level TEXT NOT NULL,message TEXT NOT NULL,observed_at_ms INTEGER NOT NULL,PRIMARY KEY(workspace_id,service));CREATE TABLE IF NOT EXISTS runtime_controls(workspace_id TEXT NOT NULL,key TEXT NOT NULL,value TEXT NOT NULL,actor TEXT NOT NULL,reason TEXT NOT NULL,updated_at_ms INTEGER NOT NULL,PRIMARY KEY(workspace_id,key));INSERT INTO runtime_schema_metadata(key,value)VALUES('schema_version','10')ON CONFLICT(key)DO UPDATE SET value=excluded.value;");}
std::uint64_t SqliteTelemetryRepository::next(std::string_view table){if(table!="runtime_audit"&&table!="runtime_alerts")throw std::invalid_argument("invalid runtime id table");return db_.next_sequence("runtime."+std::string{table});}std::uint64_t SqliteTelemetryRepository::next_audit_id(){return next("runtime_audit");}std::uint64_t SqliteTelemetryRepository::next_alert_id(){return next("runtime_alerts");}
void SqliteTelemetryRepository::append_audit(const AuditRecord&v){Statement s{db_,"INSERT INTO runtime_audit(id,workspace_id,category,actor,entity_type,entity_id,message,payload_json,created_at_ms)VALUES(?,?,?,?,?,?,?,?,?);"};s.bind(1,id64(v.id));s.bind(2,v.workspace_id);s.bind(3,v.category);s.bind(4,v.actor);s.bind(5,v.entity_type);s.bind(6,v.entity_id);s.bind(7,v.message);s.bind(8,v.payload_json);s.bind(9,ms(v.created_at));s.execute();}
std::vector<AuditRecord>SqliteTelemetryRepository::load_audit(std::size_t n){Statement s{db_,"SELECT id,workspace_id,category,actor,entity_type,entity_id,message,payload_json,created_at_ms FROM runtime_audit WHERE workspace_id=? ORDER BY id DESC LIMIT ?;"};s.bind(1,workspace_id_);s.bind(2,static_cast<std::int64_t>(n));std::vector<AuditRecord>r;while(s.step())r.push_back({static_cast<std::uint64_t>(s.column_int64(0)),s.column_text(1),s.column_text(2),s.column_text(3),s.column_text(4),s.column_text(5),s.column_text(6),s.column_text(7),tp(s.column_int64(8))});return r;}
void SqliteTelemetryRepository::save_trace(const TraceSpan&v){Statement s{db_,"INSERT INTO runtime_traces(span_id,trace_id,parent_span_id,workspace_id,service,operation,status,attributes_json,started_at_ms,ended_at_ms)VALUES(?,?,?,?,?,?,?,?,?,?)ON CONFLICT(span_id)DO UPDATE SET status=excluded.status,attributes_json=excluded.attributes_json,ended_at_ms=excluded.ended_at_ms;"};s.bind(1,v.span_id);s.bind(2,v.trace_id);if(v.parent_span_id)s.bind(3,*v.parent_span_id);else s.bind_null(3);s.bind(4,v.workspace_id);s.bind(5,v.service);s.bind(6,v.operation);s.bind(7,v.status);s.bind(8,v.attributes_json);s.bind(9,ms(v.started_at));if(v.ended_at)s.bind(10,ms(*v.ended_at));else s.bind_null(10);s.execute();}
std::vector<TraceSpan>SqliteTelemetryRepository::load_traces(std::size_t n){Statement s{db_,"SELECT trace_id,span_id,parent_span_id,workspace_id,service,operation,status,attributes_json,started_at_ms,ended_at_ms FROM runtime_traces WHERE workspace_id=? ORDER BY started_at_ms DESC LIMIT ?;"};s.bind(1,workspace_id_);s.bind(2,static_cast<std::int64_t>(n));std::vector<TraceSpan>r;while(s.step()){TraceSpan v;v.trace_id=s.column_text(0);v.span_id=s.column_text(1);if(!s.column_is_null(2))v.parent_span_id=s.column_text(2);v.workspace_id=s.column_text(3);v.service=s.column_text(4);v.operation=s.column_text(5);v.status=s.column_text(6);v.attributes_json=s.column_text(7);v.started_at=tp(s.column_int64(8));if(!s.column_is_null(9))v.ended_at=tp(s.column_int64(9));r.push_back(std::move(v));}return r;}
void SqliteTelemetryRepository::append_metric(const MetricSample&v){Statement s{db_,"INSERT INTO runtime_metrics(workspace_id,name,value,unit,labels_json,created_at_ms)VALUES(?,?,?,?,?,?);"};s.bind(1,v.workspace_id);s.bind(2,v.name);s.bind(3,v.value);s.bind(4,v.unit);s.bind(5,v.labels_json);s.bind(6,ms(v.created_at));s.execute();}
std::vector<MetricSample>SqliteTelemetryRepository::load_metrics(std::string_view name,std::size_t n){Statement s{db_,name.empty()?"SELECT workspace_id,name,value,unit,labels_json,created_at_ms FROM runtime_metrics WHERE workspace_id=? ORDER BY id DESC LIMIT ?;":"SELECT workspace_id,name,value,unit,labels_json,created_at_ms FROM runtime_metrics WHERE workspace_id=? AND name=? ORDER BY id DESC LIMIT ?;"};s.bind(1,workspace_id_);if(name.empty())s.bind(2,static_cast<std::int64_t>(n));else{s.bind(2,name);s.bind(3,static_cast<std::int64_t>(n));}std::vector<MetricSample>r;while(s.step())r.push_back({s.column_text(0),s.column_text(1),s.column_double(2),s.column_text(3),s.column_text(4),tp(s.column_int64(5))});return r;}
void SqliteTelemetryRepository::save_alert(const AlertRecord&v){Statement s{db_,"INSERT INTO runtime_alerts(id,workspace_id,severity,source,code,message,details_json,active,created_at_ms,acknowledged_at_ms)VALUES(?,?,?,?,?,?,?,?,?,?)ON CONFLICT(id)DO UPDATE SET active=excluded.active,message=excluded.message,details_json=excluded.details_json,acknowledged_at_ms=excluded.acknowledged_at_ms;"};s.bind(1,id64(v.id));s.bind(2,v.workspace_id);s.bind(3,to_string(v.severity));s.bind(4,v.source);s.bind(5,v.code);s.bind(6,v.message);s.bind(7,v.details_json);s.bind(8,static_cast<std::int64_t>(v.active));s.bind(9,ms(v.created_at));if(v.acknowledged_at)s.bind(10,ms(*v.acknowledged_at));else s.bind_null(10);s.execute();}
std::vector<AlertRecord>SqliteTelemetryRepository::load_active_alerts(){Statement s{db_,"SELECT id,workspace_id,severity,source,code,message,details_json,active,created_at_ms,acknowledged_at_ms FROM runtime_alerts WHERE workspace_id=? AND active=1 ORDER BY id DESC;"};s.bind(1,workspace_id_);std::vector<AlertRecord>r;while(s.step()){AlertRecord v;v.id=static_cast<std::uint64_t>(s.column_int64(0));v.workspace_id=s.column_text(1);v.severity=severity(s.column_text(2));v.source=s.column_text(3);v.code=s.column_text(4);v.message=s.column_text(5);v.details_json=s.column_text(6);v.active=s.column_int64(7)!=0;v.created_at=tp(s.column_int64(8));if(!s.column_is_null(9))v.acknowledged_at=tp(s.column_int64(9));r.push_back(std::move(v));}return r;}
void SqliteTelemetryRepository::save_service_health(const ServiceHealth&v,std::string_view w){Statement s{db_,"INSERT INTO runtime_service_health(workspace_id,service,state,level,message,observed_at_ms)VALUES(?,?,?,?,?,?)ON CONFLICT(workspace_id,service)DO UPDATE SET state=excluded.state,level=excluded.level,message=excluded.message,observed_at_ms=excluded.observed_at_ms;"};s.bind(1,w);s.bind(2,v.service);s.bind(3,to_string(v.state));s.bind(4,to_string(v.level));s.bind(5,v.message);s.bind(6,ms(v.observed_at));s.execute();}
std::vector<ServiceHealth>SqliteTelemetryRepository::load_service_health(){Statement s{db_,"SELECT service,state,level,message,observed_at_ms FROM runtime_service_health WHERE workspace_id=? ORDER BY service;"};s.bind(1,workspace_id_);std::vector<ServiceHealth>r;while(s.step()){ServiceHealth v;v.service=s.column_text(0);v.state=state(s.column_text(1));v.level=level(s.column_text(2));v.message=s.column_text(3);v.observed_at=tp(s.column_int64(4));r.push_back(std::move(v));}return r;}
void SqliteTelemetryRepository::set_control(const ControlRecord&v){Statement s{db_,"INSERT INTO runtime_controls(workspace_id,key,value,actor,reason,updated_at_ms)VALUES(?,?,?,?,?,?)ON CONFLICT(workspace_id,key)DO UPDATE SET value=excluded.value,actor=excluded.actor,reason=excluded.reason,updated_at_ms=excluded.updated_at_ms;"};s.bind(1,v.workspace_id);s.bind(2,v.key);s.bind(3,v.value);s.bind(4,v.actor);s.bind(5,v.reason);s.bind(6,ms(v.updated_at));s.execute();}
std::optional<ControlRecord>SqliteTelemetryRepository::get_control(std::string_view k){Statement s{db_,"SELECT workspace_id,key,value,actor,reason,updated_at_ms FROM runtime_controls WHERE workspace_id=? AND key=?;"};s.bind(1,workspace_id_);s.bind(2,k);if(!s.step())return std::nullopt;return ControlRecord{s.column_text(0),s.column_text(1),s.column_text(2),s.column_text(3),s.column_text(4),tp(s.column_int64(5))};}
}
