#include "telemetry.hpp"
#include <chrono>
#include <sstream>
namespace exotic::runtime {namespace {std::atomic<std::uint64_t> seq{1};std::string token(){auto n=seq.fetch_add(1);auto t=std::chrono::duration_cast<std::chrono::microseconds>(Clock::now().time_since_epoch()).count();return std::to_string(t)+"-"+std::to_string(n);}}
AuditTimeline::AuditTimeline(TelemetryRepository&r,std::string w):repo_(r),workspace_id_(std::move(w)){}void AuditTimeline::emit(std::string c,std::string a,std::string et,std::string ei,std::string m,std::string p){AuditRecord v;v.id=repo_.next_audit_id();v.workspace_id=workspace_id_;v.category=std::move(c);v.actor=std::move(a);v.entity_type=std::move(et);v.entity_id=std::move(ei);v.message=std::move(m);v.payload_json=std::move(p);repo_.append_audit(v);}
Metrics::Metrics(TelemetryRepository&r,std::string w):repo_(r),workspace_id_(std::move(w)){}void Metrics::record(std::string n,double v,std::string u,std::string l){repo_.append_metric({workspace_id_,std::move(n),v,std::move(u),std::move(l),Clock::now()});}
Alerts::Alerts(TelemetryRepository&r,std::string w):repo_(r),workspace_id_(std::move(w)){}std::uint64_t Alerts::raise(AlertSeverity s,std::string src,std::string code,std::string m,std::string d){for(auto&a:repo_.load_active_alerts())if(a.source==src&&a.code==code){a.severity=s;a.message=std::move(m);a.details_json=std::move(d);repo_.save_alert(a);return a.id;}AlertRecord a;a.id=repo_.next_alert_id();a.workspace_id=workspace_id_;a.severity=s;a.source=std::move(src);a.code=std::move(code);a.message=std::move(m);a.details_json=std::move(d);repo_.save_alert(a);return a.id;}void Alerts::clear(std::string_view src,std::string_view code){for(auto&a:repo_.load_active_alerts())if(a.source==src&&a.code==code){a.active=false;a.acknowledged_at=Clock::now();repo_.save_alert(a);}}
TraceScope::TraceScope(TelemetryRepository&r,std::string w,std::string s,std::string o,std::optional<std::string>p):repo_(r){span_.trace_id=p.value_or(token());span_.span_id=token();span_.parent_span_id=std::move(p);span_.workspace_id=std::move(w);span_.service=std::move(s);span_.operation=std::move(o);repo_.save_trace(span_);}TraceScope::~TraceScope(){if(!closed_)close("abandoned","{}");}void TraceScope::success(std::string a){close("success",std::move(a));}void TraceScope::fail(std::string a){close("failure",std::move(a));}void TraceScope::close(std::string s,std::string a){if(closed_)return;span_.status=std::move(s);span_.attributes_json=std::move(a);span_.ended_at=Clock::now();repo_.save_trace(span_);closed_=true;}
}
