#include "autonomy_kernel.hpp"
#include <utility>
namespace exotic::autonomy {
AutonomyKernel::AutonomyKernel(persistence::AutonomyRepository&r):repository_(r){for(auto&o:r.load_objectives())objectives_.emplace(o.id,std::move(o));for(auto&p:r.load_proposals())proposals_.emplace(p.id,std::move(p));for(auto&o:r.load_operations())operations_.emplace(o.id,std::move(o));}
void AutonomyKernel::audit(std::string event_type,std::string entity_type,std::uint64_t entity_id,std::string actor,std::string message){AuditEvent e;e.id=repository_.next_audit_event_id();e.event_type=std::move(event_type);e.entity_type=std::move(entity_type);e.entity_id=entity_id;e.actor=std::move(actor);e.message=std::move(message);repository_.append_audit_event(e);}
ObjectiveId AutonomyKernel::create_objective(Objective o){o.id=repository_.next_objective_id();o.status=ObjectiveStatus::Active;o.created_at=Clock::now();repository_.save_objective(o);audit("objective.created","objective",o.id,"exotic.kernel","Objective created.");auto id=o.id;objectives_.emplace(id,std::move(o));return id;}
ProposalId AutonomyKernel::submit_proposal(Proposal p){if(objectives_.find(p.objective_id)==objectives_.end())throw std::invalid_argument("proposal objective does not exist");p.id=repository_.next_proposal_id();p.status=ProposalStatus::Submitted;p.created_at=Clock::now();repository_.save_proposal(p);audit("proposal.submitted","proposal",p.id,p.proposed_by,"Proposal submitted.");auto id=p.id;proposals_.emplace(id,std::move(p));return id;}
DecisionResult AutonomyKernel::evaluate_proposal(ProposalId id){auto it=proposals_.find(id);if(it==proposals_.end())return{DecisionType::Deny,"Proposal was not found."};auto& p=it->second;auto result=decision_gate_.evaluate(p);if(result.decision==DecisionType::Approve)p.status=ProposalStatus::Approved;else if(result.decision==DecisionType::Deny)p.status=ProposalStatus::Rejected;repository_.save_proposal(p);audit("proposal.evaluated","proposal",p.id,"exotic.decision_gate",result.reason);return result;}
std::optional<OperationId>AutonomyKernel::execute_proposal(ProposalId id,std::string agent){auto it=proposals_.find(id);if(it==proposals_.end()||it->second.status!=ProposalStatus::Approved)return std::nullopt;auto& p=it->second;OperationRecord o;o.id=repository_.next_operation_id();o.objective_id=p.objective_id;o.proposal_id=p.id;o.agent_id=std::move(agent);o.status=OperationStatus::Running;o.started_at=Clock::now();for(const auto&step:p.plan.steps)o.execution_trace.push_back("Executed: "+step.name+" — "+step.description);o.status=OperationStatus::Verifying;repository_.save_operation(o);p.status=ProposalStatus::Executing;repository_.save_proposal(p);audit("operation.started","operation",o.id,o.agent_id,"Operation execution started.");auto oid=o.id;operations_.emplace(oid,std::move(o));return oid;}
VerificationResult AutonomyKernel::verify_operation(OperationId id){auto it=operations_.find(id);if(it==operations_.end())return{false,0.0,{"Operation was not found."},{}};auto&o=it->second;VerificationResult r;r.passed=!o.execution_trace.empty();r.confidence=r.passed?0.95:0.0;if(r.passed){r.findings.push_back("All planned steps produced execution records.");o.status=OperationStatus::Completed;o.completed_at=Clock::now();auto p=proposals_.find(o.proposal_id);if(p!=proposals_.end()){p->second.status=ProposalStatus::Completed;repository_.save_proposal(p->second);}}else{r.findings.push_back("No execution trace was produced.");r.corrections.push_back("Inspect the executor and retry the operation.");o.status=OperationStatus::Failed;o.failure_reason="Verification found no executed steps.";}o.verification=r;repository_.save_operation(o);audit(r.passed?"operation.verified":"operation.verification_failed","operation",o.id,"exotic.verification",r.passed?"Operation passed verification.":"Operation failed verification.");return r;}
bool AutonomyKernel::pause_operation(OperationId id){auto it=operations_.find(id);if(it==operations_.end()||it->second.status!=OperationStatus::Running)return false;it->second.status=OperationStatus::Paused;repository_.save_operation(it->second);audit("operation.paused","operation",id,"exotic.kernel","Operation paused.");return true;}
bool AutonomyKernel::cancel_operation(OperationId id){auto it=operations_.find(id);if(it==operations_.end()||it->second.status==OperationStatus::Completed||it->second.status==OperationStatus::RolledBack)return false;it->second.status=OperationStatus::Cancelled;repository_.save_operation(it->second);audit("operation.cancelled","operation",id,"exotic.kernel","Operation cancelled.");return true;}
bool AutonomyKernel::rollback_operation(OperationId id){auto it=operations_.find(id);if(it==operations_.end())return false;it->second.execution_trace.push_back("Rollback completed.");it->second.status=OperationStatus::RolledBack;repository_.save_operation(it->second);audit("operation.rolled_back","operation",id,"exotic.kernel","Operation rolled back.");return true;}
std::optional<Objective>AutonomyKernel::objective(ObjectiveId id)const{auto i=objectives_.find(id);return i==objectives_.end()?std::nullopt:std::optional<Objective>{i->second};}std::optional<Proposal>AutonomyKernel::proposal(ProposalId id)const{auto i=proposals_.find(id);return i==proposals_.end()?std::nullopt:std::optional<Proposal>{i->second};}std::optional<OperationRecord>AutonomyKernel::operation(OperationId id)const{auto i=operations_.find(id);return i==operations_.end()?std::nullopt:std::optional<OperationRecord>{i->second};}std::vector<OperationRecord>AutonomyKernel::operations()const{std::vector<OperationRecord>v;v.reserve(operations_.size());for(auto&[id,o]:operations_){(void)id;v.push_back(o);}return v;}
}
