(() => {
  'use strict';
  const D = window.demoData;
  const state = {
    page: 'overview',
    mode: new URLSearchParams(location.search).get('live') === '1' ? 'live' : (localStorage.getItem('exotic-mode') || 'demo'),
    endpoint: localStorage.getItem('exotic-endpoint') || ((location.protocol === 'http:' || location.protocol === 'https:') ? location.origin + '/api/v1' : 'http://127.0.0.1:8787/api/v1'),
    search: '', menu: false, command: false, loading: false, simulation: false, data: structuredClone(D)
  };

  const nav = [
    ['overview','Overview','▦'],['objectives','Objectives','◎'],['proposals','Proposals','▤'],['approvals','Approvals','◆'],
    ['scheduler','Scheduler','▣','Execution'],['agents','Agents','◉'],['resources','Resources','$'],['operations','Operations','▶'],
    ['audit','Audit Timeline','≡','Trust & Diagnostics'],['traces','Traces','⌁'],['alerts','Alerts','△'],['health','System Health','⌁'],
    ['emergency','Emergency Controls','⬢','System'],['settings','Settings','⚙']
  ];
  const $ = (s, root=document) => root.querySelector(s);
  const $$ = (s, root=document) => [...root.querySelectorAll(s)];
  const esc = s => String(s ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const fmt = n => Number.isInteger(n) ? String(n) : Number(n).toFixed(1);
  const find = (items, keys) => !state.search ? items : items.filter(i => keys(i).toLowerCase().includes(state.search.toLowerCase()));
  const badge = (status,label=status) => `<span class="status status--${status}"><span class="status__dot"></span>${esc(label)}</span>`;
  const progress = (v,color='pink',label='') => `<div class="progress-wrap">${label?`<div class="progress-label"><span>${esc(label)}</span><strong>${Math.round(v)}%</strong></div>`:''}<div class="progress"><span class="bg-${color}" style="width:${Math.max(0,Math.min(100,v))}%"></span></div></div>`;
  const button = (label, action, variant='black', icon='') => `<button class="button button--${variant}" data-action="${action}">${icon?`<span>${icon}</span>`:''}${esc(label)}</button>`;
  const panel = (body,title='',cls='',accent='') => `<section class="panel ${accent?`panel--${accent}`:''} ${cls}">${title?`<header class="panel__header"><div><span class="section-mark"></span>${esc(title)}</div></header>`:''}${body}</section>`;
  const donut = (v,label,color='pink',size=120) => { const r=42,c=2*Math.PI*r,o=c*(1-v/100); return `<div class="donut donut--${color}" style="width:${size}px;height:${size}px"><svg viewBox="0 0 100 100"><circle class="donut__track" cx="50" cy="50" r="${r}"></circle><circle class="donut__value" cx="50" cy="50" r="${r}" stroke-dasharray="${c}" stroke-dashoffset="${o}"></circle></svg><div class="donut__label"><strong>${Math.round(v)}%</strong><span>${esc(label)}</span></div></div>`; };
  const lineChart = (pts,color='pink',height=180) => { pts=Array.isArray(pts)&&pts.length?pts:[{label:'--',value:0},{label:'--',value:0}]; const w=600,p=16,max=Math.max(...pts.map(x=>x.value),1),min=Math.min(...pts.map(x=>x.value),0),range=Math.max(max-min,1); const xy=pts.map((x,i)=>({x:p+i*((w-p*2)/(pts.length-1||1)),y:p+(max-x.value)*((height-p*2-18)/range)})); const path=xy.map((p,i)=>`${i?'L':'M'}${p.x},${p.y}`).join(' '); return `<div class="line-chart line-chart--${color}"><svg viewBox="0 0 ${w} ${height}" preserveAspectRatio="none">${[.25,.5,.75].map(v=>`<line x1="${p}" x2="${w-p}" y1="${height*v}" y2="${height*v}" class="chart-grid"></line>`).join('')}<path d="${path}" class="chart-line"></path>${xy.map(p=>`<circle cx="${p.x}" cy="${p.y}" r="4" class="chart-point"></circle>`).join('')}${pts.map((x,i)=>`<text x="${xy[i].x}" y="${height-2}" text-anchor="middle" class="chart-label">${esc(x.label)}</text>`).join('')}</svg></div>`; };
  const pageFrame = (title, desc, body, actions='') => `<div class="page"><div class="page-title"><div><span class="eyebrow">EXOTIC CONTINUOUS OPERATIONS</span><h1>${esc(title)}</h1><p>${esc(desc)}</p></div>${actions?`<div class="page-title__actions">${actions}</div>`:''}</div>${body}</div>`;

  function shell() {
    const d=state.data, active=nav.find(x=>x[0]===state.page);
    let lastGroup='';
    const navHtml=nav.map(x=>{ const [id,label,ic,group]=x; const groupHtml=group&&group!==lastGroup?`<div class="nav-group">${group}</div>`:''; if(group)lastGroup=group; const count=id==='approvals'?d.summary.pendingApprovals:id==='alerts'?d.summary.openAlerts:0; return `${groupHtml}<button class="nav-item ${state.page===id?'nav-item--active':''}" data-nav="${id}"><b>${ic}</b><span>${label}</span>${count?`<em class="${id==='alerts'?'nav-item__danger':''}">${count}</em>`:''}</button>`; }).join('');
    return `<div class="app-shell ${state.menu?'app-shell--menu-open':''}">
      <aside class="sidebar"><div class="brand"><img class="brand__logo" src="./er-logo.svg" alt="ER"><div><strong>EXOTIC</strong><span>OPERATIONS CONSOLE</span></div></div><nav class="sidebar__nav">${navHtml}</nav><div class="sidebar__footer"><div class="runtime-pulse"><div class="runtime-pulse__head"><span>System pulse</span><strong>${d.summary.health}%</strong></div>${progress(d.summary.health,'green')}<small>${d.summary.uptime} uptime</small></div><div class="workspace-chip"><span class="workspace-chip__mark">W</span><div><strong>Primary workspace</strong><span>${esc(d.summary.workspace)}</span></div></div></div></aside>
      <button class="sidebar-scrim" data-action="close-menu"></button>
      <main class="main-area"><header class="topbar"><div class="topbar__left"><button class="icon-button mobile-menu" data-action="open-menu">☰</button><div class="page-heading"><span>EXOTIC / ${active[1]}</span><strong>${active[1]}</strong></div></div><div class="topbar__actions"><button class="command-trigger" data-action="command"><b>⌕</b><span>Search or command</span><kbd>Ctrl K</kbd></button><div class="mode-toggle"><button data-mode="demo" class="${state.mode==='demo'?'active':''}">Demo</button><button data-mode="live" class="${state.mode==='live'?'active':''}">Live</button></div><button class="icon-button" data-action="refresh">↻</button><button class="emergency-mini ${d.summary.emergencyStop?'emergency-mini--active':''}" data-nav="emergency"><span></span>${d.summary.emergencyStop?'STOP ACTIVE':'SYSTEM ARMED'}</button></div></header><div class="content">${state.loading?'<div class="loading-bar"></div>':''}${renderPage()}</div></main>
      ${state.command?commandPalette():''}<div class="toast-stack" id="toast-stack"></div></div>`;
  }

  function renderPage(){ return ({overview,objectives,proposals,approvals,scheduler,agents,resources,operations,audit,traces,alerts,health,emergency,settings}[state.page]||overview)(); }
  function overview(){ const d=state.data,op=(d.operations&&d.operations[0])||{id:'OP-0',objective:'No live operations yet',agent:'unassigned',traceId:'TR-NONE',verification:0,status:'pending'}; return `<div class="page-grid page-grid--overview">
    <div class="overview-hero"><div><span class="eyebrow"><span class="live-dot"></span> Continuous runtime / ${d.summary.mode}</span><h1>Everything operating.<br><em>Everything visible.</em></h1><p>One control surface for objectives, governance, agents, resources, execution, verification, and recovery.</p><div class="hero-actions">${button(state.simulation?'Simulation running':'Run end-to-end simulation','simulate','pink','▶')}${button('Inspect operations','nav-operations','white','▣')}</div></div><div class="hero-orbit"><div class="orbit orbit--1"></div><div class="orbit orbit--2"></div><div class="orbit orbit--3"></div><div class="orbit-core">ER</div><span class="orbit-node orbit-node--pink"></span><span class="orbit-node orbit-node--yellow"></span><span class="orbit-node orbit-node--blue"></span></div></div>
    <div class="stats-row">${stat('Runtime health',d.summary.health+'%','All critical services online','green','⌁','healthy')}${stat('Active operations',d.summary.activeOperations,d.summary.queuedJobs+' jobs queued','pink','▶','running')}${stat('Available agents',d.summary.activeAgents,'Across 7 specialties','blue','◉','healthy')}${stat('Pending approvals',d.summary.pendingApprovals,'$55.50 awaiting authority','yellow','◆','warning')}</div>
    ${panel(lineChart(d.throughput,'pink',210),'Operations throughput','overview-throughput')}
    ${panel(`<div class="current-operation"><div class="current-operation__id"><span>${op.id}</span><strong>${esc(op.objective)}</strong><small>${esc(op.agent)} · ${op.traceId}</small></div>${donut(op.verification,'verified','blue',130)}</div><div class="stage-track">${['Objective','Proposal','Assignment','Authority','Resources','Execution','Verification'].map((s,i)=>`<div class="stage ${i<6?'stage--done':'stage--active'}"><span>${i<6?'✓':7}</span><small>${s}</small></div>`).join('')}</div>`,'Current operation','overview-current','blue')}
    ${panel(`<div class="service-mini-list">${d.services.slice(0,5).map(s=>`<div>${badge(s.status,'')}<span><strong>${s.name}</strong><small>${s.message}</small></span><b>${s.latency}ms</b></div>`).join('')}</div>`,'Service health','overview-services')}
    ${panel(`<div class="reliability-layout">${donut(97.6,'7-day pass','yellow',145)}<div>${lineChart(d.reliability,'yellow',125)}<div class="mini-metrics"><span><strong>99.2%</strong> verification</span><span><strong>0</strong> stuck leases</span><span><strong>4.8s</strong> recovery</span></div></div></div>`,'Reliability','overview-reliability','yellow')}
    ${panel(`<div class="compact-audit">${d.audit.slice(0,5).map(e=>`<div><span class="audit-node bg-${e.accent}"></span><time>${e.time}</time><p><strong>${e.event}</strong>${e.message}</p></div>`).join('')}</div>`,'Recent audit','overview-audit')}
  </div>`; }
  function stat(t,v,n,c,ic,s){return `<div class="stat-card stat-card--${c}"><div class="stat-card__top"><span class="stat-card__icon">${ic}</span>${badge(s)}</div><strong class="stat-card__value">${v}</strong><span class="stat-card__title">${t}</span><small>${n}</small></div>`;}

  function objectives(){ const a=find(state.data.objectives,x=>`${x.id} ${x.title} ${x.owner} ${x.status}`); return pageFrame('Objectives','Every operation begins with a measurable desired outcome.',`<div class="objective-grid">${a.map(x=>panel(`<div class="card-meta"><span>${x.id}</span>${badge(x.status)}</div><h3>${x.title}</h3><p>${x.outcome}</p>${progress(x.progress,x.progress===100?'green':x.status==='warning'?'yellow':'pink','Outcome progress')}<footer><span><strong>${x.owner}</strong> owner</span><span>${x.priority} priority</span><time>${x.updated}</time></footer>`,'','objective-card',x.priority==='Critical'?'pink':x.status==='warning'?'yellow':'blue')).join('')}</div>`,button('Export','noop','white','↓')+button('New objective','new-objective','pink','◎')); }
  function proposals(){ const a=find(state.data.proposals,x=>`${x.id} ${x.objectiveId} ${x.title} ${x.agent} ${x.status}`); const rows=a.map(x=>`<div class="data-table__row"><span><strong>${x.title}</strong><small>${x.id} · ${x.objectiveId}</small></span><span>${x.agent}</span><span class="risk risk--${x.risk.toLowerCase()}">${x.risk}</span><span>${progress(x.confidence,x.confidence>90?'green':'yellow')}<small>${x.confidence}%</small></span><span>$${x.cost.toFixed(2)}</span><span>${badge(x.status)}<small>${x.created}</small></span></div>`).join(''); return pageFrame('Proposals','Plans are evaluated for value, confidence, cost, risk, and current authority.',panel(`<div class="data-table data-table--proposals"><div class="data-table__head"><span>Proposal</span><span>Agent</span><span>Risk</span><span>Confidence</span><span>Cost</span><span>Status</span></div>${rows}</div>`,'','table-panel'),button('Create proposal','new-proposal','pink','▤')); }
  function approvals(){ const a=find(state.data.approvals,x=>`${x.id} ${x.proposal} ${x.requester} ${x.status}`); const cards=a.map(x=>panel(`<div class="card-meta"><span>${x.id}</span>${badge(x.status)}</div><h3>${x.proposal}</h3><div class="approval-facts"><div><span>Requester</span><strong>${x.requester}</strong></div><div><span>Quorum</span><strong>${x.quorum}</strong></div><div><span>Budget</span><strong>$${x.budget.toFixed(2)}</strong></div><div><span>Expires</span><strong>${x.expires}</strong></div></div><div class="role-signatures">${x.roles.map((r,i)=>`<span class="${i<Number(x.quorum.split('/')[0])?'signed':''}">◆ ${r}</span>`).join('')}</div>${x.status==='pending'?`<div class="approval-actions">${button('Reject','reject-'+x.id,'white','×')}${button('Approve','approve-'+x.id,'black','✓')}</div>`:''}`,'','approval-card',x.risk==='High'?'yellow':'blue')).join(''); return pageFrame('Approvals','Durable quorum decisions with separation of duties and immutable evidence.',`<div class="approval-grid">${cards}</div>`,`<div class="summary-pill"><strong>${state.data.summary.pendingApprovals}</strong> waiting for decision</div>`); }
  function scheduler(){ const a=find([...state.data.jobs].sort((x,y)=>y.priority-x.priority),x=>`${x.id} ${x.name} ${x.worker}`); const jobs=a.map(x=>`<div class="queue-job"><div class="queue-priority"><strong>${x.priority}</strong><span>PRI</span></div><div><span class="mono">${x.id}</span><strong>${x.name}</strong><small>${x.trigger}</small></div><div><span>Next</span><strong>${x.nextRun}</strong></div><div><span>Worker</span><strong>${x.worker}</strong></div><div>${badge(x.status)}${x.attempts?`<small>${x.attempts} retry</small>`:''}</div><b>›</b></div>`).join(''); const lanes=a.slice(0,4).map((j,i)=>`<div><label>${j.name}</label><span class="schedule-block schedule-block--${i%3}" style="left:${9+i*17}%;width:${11+i*3}%">${j.id}</span></div>`).join(''); return pageFrame('Scheduler','Persistent jobs, leases, retries, dependencies, and recurring triggers.',`<div class="scheduler-layout">${panel(`<div class="queue-list">${jobs}</div>`,'Queue by priority','scheduler-queue')}${panel(`<div class="hour-strip">${Array.from({length:12},(_,i)=>`<span>${String(i*2).padStart(2,'0')}:00</span>`).join('')}</div><div class="schedule-lanes">${lanes}</div>`,'24-hour schedule','scheduler-timeline','yellow')}${panel(`<div class="capacity-grid">${['Supervisor-01','Trust-02','Resource-01','Archive-01'].map((w,i)=>`<div><span class="agent-avatar">${w.slice(0,2)}</span><strong>${w}</strong>${progress([64,42,81,12][i],i===2?'yellow':'blue')}<small>${[3,2,4,1][i]} / 5 slots</small></div>`).join('')}</div>`,'Worker capacity','scheduler-capacity')}</div>`,button('Drain workers','drain','white','Ⅱ')+button('Schedule job','new-job','pink','▣')); }
  function agents(){ const a=find(state.data.agents,x=>`${x.id} ${x.name} ${x.role} ${x.capabilities.join(' ')}`); return pageFrame('Agents','Durable identities, capability evidence, health, trust, load, and cost.',`<div class="agent-grid">${a.map(x=>panel(`<div class="agent-card__head"><span class="agent-avatar agent-avatar--large">${x.name.split(' ').map(w=>w[0]).join('').slice(0,2)}</span><div><h3>${x.name}</h3><p>${x.role}</p></div>${badge(x.status)}</div><div class="agent-model">▣ <span>${x.model}</span><small>${x.cost}</small></div><div class="agent-score-row">${donut(x.trust,'trust','pink',92)}${donut(x.reliability,'reliable','blue',92)}${donut(x.load,'load',x.load>75?'yellow':'green',92)}</div><div class="tag-list">${x.capabilities.map(c=>`<span>${c}</span>`).join('')}</div><footer><span>Heartbeat <strong>${x.lastHeartbeat}</strong></span><button class="text-button">Inspect evidence →</button></footer>`,'','agent-card',x.status==='warning'?'yellow':'blue')).join('')}</div>`,button('Rebalance','rebalance','white','↻')+button('Register agent','new-agent','pink','◉')); }
  function resources(){ const a=find(state.data.resources,x=>`${x.name} ${x.unit}`); const summary=`<div class="resource-summary">${panel('<span>Current monetary spend</span><strong>$172.00</strong><small>57.3% of monthly authority</small>','','','pink')}${panel('<span>Active reservations</span><strong>8</strong><small>$23.40 expected cost</small>','','','yellow')}${panel('<span>Forecast accuracy</span><strong>94.8%</strong><small>Across verified operations</small>','','','blue')}${panel('<span>Open circuits</span><strong>0</strong><small>All workloads admitted normally</small>')}</div>`; const cards=a.map(x=>{const p=x.used/x.limit*100,f=x.forecast/x.limit*100;return panel(`<div class="resource-card__head"><h3>${x.name}</h3>${badge(x.status)}</div><div class="resource-amount"><strong>${fmt(x.used)}</strong><span>/ ${fmt(x.limit)} ${x.unit}</span></div>${progress(p,x.status==='warning'?'yellow':'blue')}<div class="forecast-line"><span>Forecast</span><strong>${fmt(x.forecast)}</strong><small>${f.toFixed(0)}% of limit</small></div>`,'','resource-card',x.status==='warning'?'yellow':'blue')}).join(''); return pageFrame('Resources','Hierarchical budgets, atomic reservations, forecasting, and circuit breakers.',summary+`<div class="resource-grid">${cards}</div>`,button('Cost report','noop','white','↓')+button('Adjust budget','adjust-budget','pink','$')); }
  function operations(){ const a=find(state.data.operations,x=>`${x.id} ${x.objective} ${x.agent} ${x.traceId}`); const rows=a.map(x=>`<button class="data-table__row" data-operation="${x.id}"><span><strong>${x.objective}</strong><small>${x.id} · ${x.traceId}</small></span><span>${x.agent}</span><span>${x.started}</span><span class="mono">${x.duration}</span><span>${progress(x.verification,x.verification>90?'green':x.verification>60?'yellow':'pink')}<small>${x.verification}%</small></span><span>${badge(x.status)}</span><b>›</b></button>`).join(''); return pageFrame('Operations','Execution records are not complete until independent verification passes.',panel(`<div class="data-table data-table--operations"><div class="data-table__head"><span>Operation</span><span>Assigned agent/team</span><span>Started</span><span>Duration</span><span>Verification</span><span>Status</span><span></span></div>${rows}</div>`,'','table-panel'),button('Start controlled operation','simulate','pink','▶')); }
  function audit(){ const a=find(state.data.audit,x=>`${x.id} ${x.actor} ${x.event} ${x.message}`); const t=a.map((x,i)=>`<div class="audit-event"><div class="audit-event__rail"><span class="bg-${x.accent}"></span>${i<a.length-1?'<i></i>':''}</div><time>${x.time}<small>${x.id}</small></time><div><div class="audit-event__title"><strong>${x.event}</strong><span>${x.actor}</span></div><p>${x.message}</p><code>${x.entity}</code></div></div>`).join(''); return pageFrame('Audit Timeline','Append-only evidence across autonomy, governance, resources, agents, and runtime services.',panel(`<div class="audit-timeline">${t}</div>`,'','audit-panel'),button('Filters','noop','white','▽')+button('Export evidence','noop','black','↓')); }
  function traces(){ const s=state.data.traces; const sum=`<div class="trace-summary">${panel('<span>Total duration</span><strong>4.18s</strong><small>6 spans</small>')}${panel('<span>Critical path</span><strong>autonomy</strong><small>1.29s</small>','','','blue')}${panel('<span>Database time</span><strong>142ms</strong><small>24 queries</small>','','','yellow')}${panel('<span>Verification</span><strong>87%</strong><small>still running</small>','','','pink')}</div>`; const rows=s.map((x,i)=>`<div class="trace-row"><div><strong>${x.service}</strong><small>${x.operation}</small></div><div class="trace-track"><span class="trace-span trace-span--${i%3}" style="left:${x.start}%;width:${Math.max(x.duration,4)}%"><b>${x.duration*41}ms</b></span></div>${badge(x.status)}</div>`).join(''); const ctx=JSON.stringify({trace_id:'TR-77A2',objective_id:'OBJ-1042',proposal_id:'PRP-882',assignment_id:'ASN-1204',reservation_id:'RSV-3302',operation_id:'OP-9008',simulation:true},null,2); return pageFrame('Traces','End-to-end execution spans across every runtime boundary.',sum+panel(`<div class="trace-axis"><span>0ms</span><span>1s</span><span>2s</span><span>3s</span><span>4s</span></div>${rows}`,'Waterfall','trace-waterfall')+panel(`<pre>${esc(ctx)}</pre>`,'Trace context','trace-context'),'<span class="summary-pill">Trace TR-77A2</span>'); }
  function alerts(){ const a=find(state.data.alerts,x=>`${x.id} ${x.title} ${x.source}`); return pageFrame('Alerts','Actionable runtime signals with source, severity, ownership, and evidence.',`<div class="alert-list">${a.map(x=>panel(`<div class="alert-card__icon">△</div><div><div class="card-meta"><span>${x.id} · ${x.source}</span><time>${x.time}</time></div><h3>${x.title}</h3><p>${x.detail}</p></div><div>${x.acknowledged?badge('completed','Acknowledged'):button('Acknowledge','ack-'+x.id,x.severity==='critical'?'danger':'white')}</div>`,'',`alert-card alert-card--${x.severity}`)).join('')}</div>`,`<span class="summary-pill"><strong>${state.data.summary.openAlerts}</strong> open alerts</span>`); }
  function health(){ const d=state.data,h=d.services.filter(x=>x.status==='healthy').length; const hero=`<div class="health-hero">${donut(d.summary.health,'system health','green',180)}<div><span class="eyebrow">CONTINUOUS SUPERVISION ACTIVE</span><h2>${h} of ${d.services.length} services healthy</h2><p>No stuck leases, no orphaned reservations, and no broken audit sequence detected.</p><div class="health-facts"><span><strong>4.8s</strong> recovery target</span><span><strong>1s</strong> supervisor heartbeat</span><span><strong>0</strong> critical failures</span></div></div></div>`; const cards=d.services.map(x=>panel(`<div class="service-card__head"><span class="service-shape">▣</span><div><h3>${x.name}</h3><small>version ${x.version}</small></div>${badge(x.status)}</div><p>${x.message}</p><footer><span>Latency <strong>${x.latency}ms</strong></span><span>Heartbeat <strong>${x.heartbeat}</strong></span></footer>`,'','service-card',x.status==='warning'?'yellow':'blue')).join(''); return pageFrame('System Health','Dependency-ordered services, heartbeats, latency, supervision, and recovery.',hero+`<div class="service-grid">${cards}</div>`,button('Run health sweep','refresh','black','↻')); }
  function emergency(){ const a=state.data.summary.emergencyStop; const zone=`<div class="emergency-zone ${a?'emergency-zone--active':''}"><div class="emergency-zone__symbol">${a?'■':'⬢'}</div><span class="eyebrow">${a?'EMERGENCY STOP ACTIVE':'GOVERNED EXECUTION ARMED'}</span><h2>${a?'External execution is blocked.':'The runtime is operating normally.'}</h2><p>${a?'Queued work remains durable, but no governed external operation may begin until the stop is cleared.':'Activating the emergency stop will block new governed execution while preserving state, evidence, and recovery data.'}</p><button class="emergency-button ${a?'emergency-button--clear':''}" data-action="toggle-emergency"><b>${a?'▶':'■'}</b><strong>${a?'CLEAR EMERGENCY STOP':'ACTIVATE EMERGENCY STOP'}</strong><span>${a?'Requires operator confirmation':'Immediate system-wide authority override'}</span></button><div class="emergency-checks">${['Governance control durable','Resource shutdown synchronized','Scheduler admission blocked','Audit evidence appended','Recovery state preserved'].map(x=>`<span>✓ ${x}</span>`).join('')}</div></div>`; const actions=`<div class="emergency-actions">${panel(`<p>Drain scheduler workers, reconcile active reservations, flush telemetry, and stop services in reverse dependency order.</p>${button('Begin controlled shutdown','shutdown','white','Ⅱ')}`,'Controlled shutdown')}${panel(`<p>Force all approved work into simulation-only mode without stopping observation, planning, or verification.</p>${button('Enable simulation lock','simulation-lock','yellow','⬢')}`,'Simulation lock')}${panel(`<p>Create an immutable incident checkpoint containing controls, alerts, traces, operations, and service state.</p>${button('Capture incident package','capture','blue','↓')}`,'Incident evidence')}</div>`; return pageFrame('Emergency Controls','System-wide controls override all grants, approvals, scheduler leases, and resource authority.',zone+actions); }
  function settings(){ return pageFrame('Settings','Configure the console adapter, refresh behavior, workspace display, and operator preferences.',`<div class="settings-grid">${panel(`<label>Data source<select id="setting-mode"><option value="demo" ${state.mode==='demo'?'selected':''}>Demo simulation</option><option value="live" ${state.mode==='live'?'selected':''}>Live runtime API</option></select></label><label>Runtime API endpoint<input id="setting-endpoint" value="${esc(state.endpoint)}"></label><label>Refresh interval<select><option>5 seconds</option><option>10 seconds</option><option>30 seconds</option></select></label><div class="adapter-contract"><strong>Expected adapter contract</strong><code>GET /api/v1/console/snapshot</code><code>POST /api/v1/actions/:action</code><code>GET /api/v1/health</code></div>`,'Runtime connection','settings-panel','blue')}${panel(`<div class="setting-toggle"><span><strong>Compact density</strong><small>Fit more runtime information per screen.</small></span><input type="checkbox" checked></div><div class="setting-toggle"><span><strong>Reduced motion</strong><small>Suppress nonessential interface transitions.</small></span><input type="checkbox"></div><div class="setting-toggle"><span><strong>24-hour timestamps</strong><small>Use operational time formatting.</small></span><input type="checkbox" checked></div><div class="token-preview"><span class="bg-pink"></span><span class="bg-yellow"></span><span class="bg-blue"></span><span class="bg-green"></span><span class="bg-orange"></span><span class="bg-red"></span></div>`,'Appearance','settings-panel','pink')}${panel(`<div class="setting-toggle"><span><strong>Confirm authority changes</strong><small>Require confirmation for approvals and revocations.</small></span><input type="checkbox" checked></div><div class="setting-toggle"><span><strong>Confirm emergency controls</strong><small>Protect system-wide stop and resume operations.</small></span><input type="checkbox" checked disabled></div><div class="setting-toggle"><span><strong>Default to simulation</strong><small>New operations begin in simulation unless explicitly promoted.</small></span><input type="checkbox" checked></div>`,'Operator safeguards','settings-panel','yellow')}${panel(`<div class="about-lockup"><img src="./er-logo.svg"><div><strong>EXOTIC Operations Console</strong><span>Version 1.0.0</span><p>Everything is Exotic.</p></div></div><div class="about-list"><span>Runtime contract<strong>Continuous Operations v1.0</strong></span><span>Interface mode<strong>Browser + Electron</strong></span><span>Storage<strong>Local preferences only</strong></span></div>`,'About','settings-panel')}</div>`,button('Save settings','save-settings','black','✓')); }

  function commandPalette(){ const commands=nav.filter(x=>!state.search||x[1].toLowerCase().includes(state.search.toLowerCase())).slice(0,10); return `<div class="modal-backdrop" data-action="close-command"><div class="command-palette" data-stop><div class="command-search"><b>⌕</b><input id="command-input" autofocus placeholder="Search pages, operations, agents, commands…" value="${esc(state.search)}"><kbd>ESC</kbd></div><div class="command-results">${commands.map(x=>`<button data-nav="${x[0]}"><span>${x[2]}</span><div><strong>Open ${x[1]}</strong><small>Navigation</small></div><b>›</b></button>`).join('')}<button data-action="simulate"><span>▶</span><div><strong>Run end-to-end simulation</strong><small>Runtime action</small></div><b>›</b></button></div></div></div>`; }

  function toast(message,tone='info'){ const stack=$('#toast-stack'); if(!stack)return; const el=document.createElement('div'); el.className=`toast toast--${tone}`; el.innerHTML=`<span></span>${esc(message)}`; stack.appendChild(el); setTimeout(()=>el.remove(),4000); }
  function render(){ $('#root').innerHTML=shell(); bind(); if(state.command){setTimeout(()=>$('#command-input')?.focus(),0);} }
  function bind(){
    $$('[data-nav]').forEach(el=>el.addEventListener('click',()=>{state.page=el.dataset.nav;state.menu=false;state.command=false;render();}));
    $$('[data-mode]').forEach(el=>el.addEventListener('click',()=>{state.mode=el.dataset.mode;localStorage.setItem('exotic-mode',state.mode);toast(state.mode==='live'?'Live adapter enabled; demo fallback remains active.':'Demo simulation enabled.','success');refresh();}));
    $$('[data-action]').forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();action(el.dataset.action,el);}));
    $$('[data-stop]').forEach(el=>el.addEventListener('click',e=>e.stopPropagation()));
    $$('[data-operation]').forEach(el=>el.addEventListener('click',()=>openOperation(el.dataset.operation)));
    $('#command-input')?.addEventListener('input',e=>{state.search=e.target.value;render();});
  }
  async function postLive(actionName,payload={}){const response=await fetch(state.endpoint+'/actions/'+actionName,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({actor:'console.operator',role:'operator',...payload})});let body={};try{body=await response.json();}catch{}if(!response.ok||body.ok===false)throw new Error(body.message||response.statusText);return body;}
  function normalizeSnapshot(data){const fallback=structuredClone(D);for(const key of ['summary','throughput','reliability','objectives','proposals','approvals','jobs','agents','resources','operations','audit','traces','alerts','services']){if(data?.[key]===undefined)data[key]=fallback[key];}data.summary={...fallback.summary,...data.summary};return data;}
  async function action(a,el){
    if(a==='open-menu'){state.menu=true;render();return;} if(a==='close-menu'){state.menu=false;render();return;} if(a==='command'){state.command=true;render();return;} if(a==='close-command'){state.command=false;render();return;} if(a==='nav-operations'){state.page='operations';render();return;} if(a==='refresh'){refresh(true);return;} if(a==='simulate'){simulate();return;} if(a==='toggle-emergency'){toggleEmergency();return;} if(a==='save-settings'){const m=$('#setting-mode')?.value,e=$('#setting-endpoint')?.value;state.mode=m||state.mode;state.endpoint=e||state.endpoint;localStorage.setItem('exotic-mode',state.mode);localStorage.setItem('exotic-endpoint',state.endpoint);toast('Console settings saved.','success');render();return;}
    if(a?.startsWith('approve-')||a?.startsWith('reject-')){const approve=a.startsWith('approve-'),id=a.split('-').slice(1).join('-'),x=state.data.approvals.find(v=>v.id===id);if(!x)return;if(state.mode==='live'){try{const result=await postLive(approve?'approval.approve':'approval.reject',{requestId:Number(x.requestId||String(id).replace(/\D/g,'')),reason:approve?'Approved in Operations Console':'Rejected in Operations Console'});toast(result.message,approve?'success':'warning');await refresh(false);}catch(error){toast(error.message,'error');}}else{x.status=approve?'completed':'critical';state.data.summary.pendingApprovals=Math.max(0,state.data.summary.pendingApprovals-1);toast(`${id} ${approve?'approved':'rejected'}.`,approve?'success':'warning');render();}return;}
    if(a?.startsWith('ack-')){const id=a.slice(4),x=state.data.alerts.find(v=>v.id===id);if(!x||x.acknowledged)return;if(state.mode==='live'){try{const result=await postLive('alert.acknowledge',{alertId:Number(x.alertId||String(id).replace(/\D/g,''))});toast(result.message,'success');await refresh(false);}catch(error){toast(error.message,'error');}}else{x.acknowledged=true;state.data.summary.openAlerts=Math.max(0,state.data.summary.openAlerts-1);toast(`${id} acknowledged.`,'success');render();}return;}
    if(a==='shutdown'&&state.mode==='live'){if(!confirm('Begin a controlled EXOTIC runtime shutdown?'))return;try{const result=await postLive('runtime.shutdown',{reason:'Controlled shutdown requested from Operations Console'});toast(result.message,'warning');}catch(error){toast(error.message,'error');}return;}
    if(['new-objective','new-proposal','new-job','new-agent','adjust-budget','rebalance','drain','simulation-lock','capture'].includes(a)){toast(state.mode==='live'?'This control is visible but not enabled in the v1.1 adapter.':'Demo control recorded.','info');return;}
    if(a==='noop')toast('Export/control placeholder ready for live adapter.','info');
  }
  async function refresh(showToast=false){state.loading=true;render();if(state.mode==='live'){try{const r=await fetch(state.endpoint+'/console/snapshot',{headers:{Accept:'application/json'},cache:'no-store'});if(!r.ok)throw new Error(r.status+' '+r.statusText);state.data=normalizeSnapshot(await r.json());state.data.summary.lastSync='just now';if(showToast)toast('Live runtime snapshot loaded.','success');}catch(e){state.data.summary.lastSync='live endpoint unavailable · '+e.message;if(showToast)toast('Live endpoint unavailable; preserving the last snapshot.','warning');}}await new Promise(r=>setTimeout(r,100));state.loading=false;render();}
  async function simulate(){if(state.simulation||state.data.summary.emergencyStop){toast(state.data.summary.emergencyStop?'Simulation blocked by emergency stop.':'Simulation already running.','warning');return;}if(state.mode==='live'){state.simulation=true;render();toast('Running the real Objective → Verification simulation…','info');try{const result=await postLive('simulation.run',{reason:'Operations Console live simulation'});toast(result.message,'success');await refresh(false);}catch(error){toast(error.message,'error');}finally{state.simulation=false;render();}return;}state.simulation=true;const id='OP-'+Math.floor(9100+Math.random()*800),trace='TR-'+Math.random().toString(16).slice(2,6).toUpperCase();const op={id,objective:'Console live simulation',agent:'Operator Prime + Proof',started:'now',duration:'00:00',verification:0,traceId:trace,status:'running'};state.data.operations.unshift(op);state.data.summary.activeOperations++;state.page='operations';render();toast('Simulation started: Objective → Verification.','info');const phases=[['Proposal passed the Decision Gate.',18],['Agent team assigned and authority revalidated.',38],['Resources reserved across the hierarchy.',56],['Operation executed in simulation mode.',78],['Independent verification passed.',100]];for(const [msg,p] of phases){await new Promise(r=>setTimeout(r,650));op.verification=p;op.duration='00:0'+Math.min(9,Math.ceil(p/20));state.data.audit.unshift({id:'AUD-'+Date.now(),time:new Date().toLocaleTimeString([],{hour12:false}),actor:p===100?'exotic.verification':'exotic.runtime',event:p===100?'operation.verified':'simulation.progress',entity:id,message:msg,accent:p===100?'green':'blue'});render();}op.status='completed';state.data.summary.activeOperations--;state.simulation=false;render();toast('Simulation verified. All durable stages completed.','success');}
  async function toggleEmergency(){const active=!state.data.summary.emergencyStop;if(!confirm(active?'Activate the EXOTIC emergency stop?':'Clear the emergency stop?'))return;if(state.mode==='live'){try{const result=await postLive(active?'emergency.activate':'emergency.clear',{reason:active?'Emergency stop activated from Operations Console':'Emergency stop cleared from Operations Console'});toast(result.message,active?'error':'success');await new Promise(r=>setTimeout(r,500));await refresh(false);}catch(error){toast(error.message,'error');}return;}state.data.summary.emergencyStop=active;state.data.services.forEach(s=>{if(['governance','resource-governor'].includes(s.name)){s.status=active?'critical':'healthy';s.message=active?'Emergency stop active.':'Emergency stop clear.';}});render();toast(active?'Emergency stop activated.':'Emergency stop cleared.',active?'error':'success');}
  function openOperation(id){const x=state.data.operations.find(o=>o.id===id);if(!x)return; const html=`<div class="drawer-backdrop" id="drawer"><aside class="operation-drawer"><header><div><span>${x.id}</span><h2>${x.objective}</h2></div><button class="icon-button" id="drawer-close">×</button></header><div class="drawer-status">${badge(x.status)}<span>${x.agent}</span><code>${x.traceId}</code></div>${panel(donut(x.verification,'complete',x.verification>90?'green':'blue',160),'Verification')}${panel(`<div class="drawer-chain">${['Objective created','Proposal evaluated','Team assigned','Authority validated','Resources reserved','Operation executed','Verification recorded'].map((s,i)=>`<div class="${i*15<=x.verification?'done':''}"><span>${i*15<=x.verification?'✓':i+1}</span><strong>${s}</strong><small>${i*15<=x.verification?'durable evidence present':'waiting'}</small></div>`).join('')}</div>`,'Execution chain')}<div class="drawer-actions">${button('Pause','noop','white','Ⅱ')}${button('Open trace','nav-traces','black','⌁')}</div></aside></div>`; document.body.insertAdjacentHTML('beforeend',html);$('#drawer').addEventListener('click',()=>$('#drawer').remove());$('.operation-drawer').addEventListener('click',e=>e.stopPropagation());$('#drawer-close').addEventListener('click',()=>$('#drawer').remove()); }
  document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();state.command=!state.command;render();}if(e.key==='Escape'){state.command=false;state.menu=false;render();}});
  setTimeout(()=>{render();if(state.mode==='live')refresh(false);},250);
  setInterval(()=>{if(state.mode==='live'&&!state.loading)refresh(false);},5000);
})();
